P11 config update
mxcube/mxcubecore pull request #1095
Opened 2024-12-13 13:49 UTC by agruzinov

Before starting migration to the yaml it is good to have working set of scripts for the current setup.

2024-12-13 14:43 UTC, beteva requested changes
Hi  @agruzinov, good initiative to clean up obsolete files.
As a general remark, we have removed Device and Equipment classes, so everywhere in the config files you should replace device and equipment with object. It still works if you do not do this, but since you are anyhow cleaning up, it will be better if you do it. Also will be easier when you transfer from xml to yaml.

2024-12-13 14:43 UTC, beteva commented on mxcubecore/configuration/desy_p11/beam.xml
> +<object class="P11Beam">
This probably should be DESY.P11Beam, as the file is in the DESY sub directory.

2024-12-13 14:43 UTC, beteva commented on mxcubecore/configuration/desy_p11/beam.xml
> +    <definer_type>"mirror"</definer_type>
I wonder if you have a definer mirror, than you should be having an object with a role mirror (just like aperture and slits)

2024-12-13 14:43 UTC, beteva commented on mxcubecore/configuration/desy_p11/beamstop_bcp.xml
> +<device class="P11BeamStop">
Same as above, should not this be DESY.P11BeamStop

2024-12-13 14:43 UTC, beteva commented on mxcubecore/configuration/desy_p11/characterisation.xml
> +<object class="P11EDNACharacterisation">
Same as above (DESY.P11EDNACharacterisation)

2024-12-13 14:43 UTC, beteva commented on mxcubecore/configuration/desy_p11/collimator.xml
> +<object class="P11Collimator">
Same as above.

2024-12-13 14:43 UTC, beteva commented on mxcubecore/configuration/desy_p11/detector-cover.xml
> +<device class="P11DetectorCover">
Same as above (DESY.P11DetectorCover

2024-12-13 14:43 UTC, beteva commented on mxcubecore/configuration/desy_p11/diff-aperture-mockup.xml
> +</device>
This should be as before - object, not device

2024-12-13 14:43 UTC, beteva commented on mxcubecore/configuration/desy_p11/diff-kappa-mockup.xml
> +</device>
Same here, object, not device

2024-12-13 14:43 UTC, beteva commented on mxcubecore/configuration/desy_p11/diff-kappaphi-mockup.xml
> +</device>
Revert to previous version - should be object, not device

2024-12-13 14:43 UTC, beteva commented on mxcubecore/configuration/desy_p11/door-interlock-mockup.xml
> +</device>
object and also DESY.P11DoorInterlock

2024-12-13 14:43 UTC, beteva commented on mxcubecore/configuration/desy_p11/energy.xml
> +<equipment class="P11Energy">
object, not equipment, also DESY.P11Energy

2024-12-13 16:21 UTC, agruzinov commented
Thanks for the comments @beteva! 

I was wondering if someone is using the yamllinter that can lint files annt not only show 100500 errors that needs to be changed one by one :) 
P.S.
prettier, yamlfmt still can not make yamllint happy...
Thanks!

2024-12-16 08:42 UTC, fabcor-maxiv commented
> I was wondering if someone is using the yamllinter that can lint files and not only show errors that needs to be changed one by one :)
> prettier, yamlfmt still can not make yamllint happy...

I had a very quick look at the job output. Looks like the file has a lot of "long lines". It is possible to disable the "long lines" rule for a specific file. That would be acceptable.

<https://yamllint.readthedocs.io/en/stable/disable_with_comments.html>

2025-01-27 14:42 UTC, marcus-oscarsson commented
@agruzinov, unfortunately I don't think there is formater that handles all the linting errors. I tried to find one a while back and I did not find any at the time. Perhaps someone out there have found a good tool ?

2025-03-10 17:48 UTC, beteva commented
Hi @agruzinov, Is this PR still relevant?

2025-10-21 07:06 UTC, marcus-oscarsson commented
Hi @agruzinov, do you have any update on this one, perhaps a more recent version ;)

2025-10-28 08:27 UTC, marcus-oscarsson commented
Closing this for now, feel free to reopen

2025-10-28 08:27 UTC, closed without merging