Refactoring
mxcube/mxcubecore pull request #611
Opened 2021-03-08 09:07 UTC by IvarsKarpics

* replaces HardwareRepository with mxcubecore
* added qt_import.py to utils directory. Importing from mxcubegui is strange and easiest solution is to duplicated the qt_import.py. This is open for discussion.

PR is compatible with latest changes in mxcube/mxcube

2021-03-08 15:31 UTC, rhfogh commented on HardwareObjects/EMBL/EMBLXrayImaging.py
> +from gui.utils import qt_import, Colors
Change to mxcubecore.utils?

2021-03-08 15:32 UTC, rhfogh commented on HardwareObjects/QtAxisCamera.py
> +from mxcubeqt.utils import qt_import
Change to mxcubecore.utils?

2021-03-08 15:34 UTC, rhfogh commented on HardwareObjects/DESY/MjpgStreamVideo.py
> +from gui.utils.qt_import import QImage, QPixmap
Change to mxcubecore.utils?

2021-03-08 15:34 UTC, marcus-oscarsson commented
Yes, I think that is the conclusion of one of our previous discussion. Thanks for paying attention to that,

2021-03-08 15:34 UTC, rhfogh commented on HardwareObjects/SOLEIL/PX2/PX2Qt4_LimaVideo.py
> +    from gui.utils.qt_import import *
Change to mxcubecore.utils?

Get rid of 'import *'?

2021-03-08 15:34 UTC, rhfogh commented on HardwareObjects/SOLEIL/PX2/PX2Video.py
> +from gui.utils.qt_import import QImage, QPixmap
Change to mxcubecore.utils?

2021-03-08 15:35 UTC, rhfogh commented on HardwareObjects/VaporyVideo.py
> +from gui.utils.qt_import import QImage
Change to mxcubecore.utils?

2021-03-08 15:35 UTC, rhfogh commented on HardwareObjects/VimbaVideo.py
> +from gui.utils.qt_import import QImage, QPixmap
Change to mxcubecore.utils?

2021-03-08 15:35 UTC, rhfogh commented on deprecated/HardwareObjects/mockup/VideoMockup.py
> +from gui.utils.qt_import import QImage
Change to mxcubecore.utils?

2021-03-08 15:37 UTC, marcus-oscarsson commented
And thanks @IvarsKarpics for doing this, I thought we said that Rasmus and myself would take care of it but this is just as good.

2021-03-08 15:41 UTC, rhfogh requested changes
Approve subject to commented changes

2021-03-08 16:46 UTC, marcus-oscarsson commented
I think we need to have a look at why the tests are failing

2021-03-08 21:08 UTC, IvarsKarpics commented
Hi @marcus-oscarsson  and @rhfogh  I fixed qt_import and pytest.

2021-03-09 14:35 UTC, IvarsKarpics commented on HardwareObjects/VaporyVideo.py
> +from gui.utils.qt_import import QImage
done

2021-03-10 08:56 UTC, IvarsKarpics commented
Hi @marcus-oscarsson  and @rhfogh 

Are you ok with the PR. Can we merge it and move further?

2021-03-10 09:00 UTC, rhfogh commented
I am OK.
Yours,
Rasmus

On Wed, 10 Mar 2021 at 08:57, Ivars Karpics <notifications@github.com>
wrote:

> Hi @marcus-oscarsson <https://github.com/marcus-oscarsson> and @rhfogh
> <https://github.com/rhfogh>
>
> Are you ok with the PR. Can we merge it and move further?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mxcube/mxcubecore/pull/611#issuecomment-795109651>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACK5QEHCR667U6TDEDFJY4TTC4X55ANCNFSM4YZAIHWQ>
> .
>

2021-03-10 13:44 UTC, merged

2021-03-10 13:47 UTC, IvarsKarpics commented
Excellent!!! Thank you!