Clean up abstract procedure
mxcube/mxcubecore pull request #620
Opened 2021-06-02 07:00 UTC by IvarsKarpics

* Added variables offline_processing_methods and online_processing_methods to the Beamline. Both are lists of strings and are populated based on beamline_config.yml. Processing methods are are listed in the processing widget. For example: offline_processing_methods  = ["EDNAProc", "AutoProc"] will result in displaying "Run offline processing (EDNAProc, AutoProc)". If not method is defined then the checkbox is unchecked and disabled.
* Renamed run_processing_parallel to run_offline_processing. True will check the checkbox "Run offline processing" in processing_widget.
* Cleaned up AbstractCollect: removed not used imports, inherit class from AbstractProcedure, implemented _pre_execute, _execute and post_execute. Currently methods are empty and in the next PR will be reviewed.
* AbstractOnlineProcessing is inherited now from AbstractProcedure. Removed not used code.
* Cleaned AbstractProcedure. For sure it is not the final version, but at least to start with.
* CollectMockup reviewed and cleaned.
* queue_entry is modified based on signals emitted by CollectMockup, OnlineProcessingMockup (both based on AbstractProcedure)

Now mockup data collection is running and there are online processing results displayed.

2021-06-03 14:19 UTC, rhfogh approved these changes
This is too big to look at in detail - we shall have to wait till it is in, try it out, and then propose any changes. But it looks good and clean. Onward it is!

2021-06-03 15:14 UTC, marcus-oscarsson commented
Hm, we are still using the old fashioned AbstractMultiCollect so we can use this a it is with the changes to queue_entry, could you make a separate queue_entry for your tests. We need to be able to use AbstractMultiCollect for a little longer.

2021-06-03 15:15 UTC, marcus-oscarsson requested changes

2021-06-03 15:15 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/queue_entry.py
> -
So these changes would be problematic for us, as we are still not using AbstractProcedure for the collect

2021-06-15 09:32 UTC, beteva commented on mxcubecore/HardwareObjects/Beamline.py
> +
Could you, please, change the comment and explain the difference between tasks and merhods

2021-06-15 09:32 UTC, beteva commented on mxcubecore/HardwareObjects/abstract/AbstractProcedure.py
>  # Temporary definition should use common denfinition from
Maybe it is a good time to change the states implementation, as specified in the comment.

2021-06-15 11:49 UTC, rhfogh approved these changes
There is too much here for me to judge the details, but it looks about right, and we shall sort out the final details ater in any case.

2021-06-15 11:57 UTC, rhfogh commented on mxcubecore/HardwareObjects/abstract/AbstractProcedure.py
> +class AbstractProcedure(HardwareObject):
Any paeticular reason to stay with xml configuration instead of moving to yaml configuration? From the current class names I think a yaml-configured object should have been HardwareObjectYaml, so there is another alternative to ConfiguredObject

2022-05-17 15:29 UTC, rhfogh commented
Is this PR still relevant, or has it been superseded by events?

2022-05-17 18:28 UTC, marcus-oscarsson commented
Indeed, I think we can consider this superseded

2022-05-17 18:28 UTC, closed without merging