Update of EMBL hardware objects
mxcube/mxcubecore pull request #637
Opened 2021-08-13 09:23 UTC by IvarsKarpics

2021-08-14 07:56 UTC, rhfogh commented on mxcubecore/HardwareObjects/EMBL/EMBLBeam.py
> +        print("ver ", value)
Remove?

2021-08-14 12:49 UTC, rhfogh requested changes
Looking good.
One comment - the one about total_dose_absorbed being considered equal to flux.get_value() needs to bea ddressed; the rest can be merged in and looked at later, if desired.

2021-08-16 07:56 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/EMBL/EMBLBeamline.py
>          """PPU control Hardware object
done

2021-08-16 07:56 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/EMBL/EMBLBeamline.py
> +        """PPU control Hardware object
done

2021-08-16 07:57 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/EMBL/EMBLCollect.py
> +        return float("%.3e" % HWR.beamline.flux.get_value())
Hi @rhfogh 
I would suggest to go on and merge the PR and come back to this issue via an another PR or issue.

2021-08-16 07:57 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/EMBL/EMBLOnlineProcessing.py
> +        except BaseException:
Reverted to Exception

2021-08-16 07:58 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/EMBL/EMBLOnlineProcessing.py
> +    def get_spacegroup_dict(self, proc_params, space_group_name):
I will have a look how it would be possible to use the SPACEGROUP_DATA from enumerables

2021-08-16 08:13 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/EMBL/EMBLCollect.py
> +        return float("%.3e" % HWR.beamline.flux.get_value())
Ok, ill let you either do a issue or a mental note (as its EMBL specific code) and Ill merge the code.

2021-08-16 08:17 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/EMBL/EMBLOnlineProcessing.py
> +    def get_spacegroup_dict(self, proc_params, space_group_name):
:+1:

2021-08-16 08:17 UTC, merged

2021-08-16 08:43 UTC, rhfogh commented on mxcubecore/HardwareObjects/EMBL/EMBLOnlineProcessing.py
> +    def get_spacegroup_dict(self, proc_params, space_group_name):
The SPACEGROUP_DATA may need changing for that. Since I believe I am the only one usieng them, I am very willing to make any changes required.