Fixes after testing mxcubeqt with python3/qt5
mxcube/mxcubecore pull request #639
Opened 2021-08-16 13:39 UTC by IvarsKarpics

Here are some changes, fixes after testing the latest version of mxcubecore with python3/qt5 on the beamline p13

- Beamline.py: 
1. added boolean run_offline_processing to indicate if by default the offline autoprocessing will be launched. 
2. added list variable offline_processing_methods and online_processing_methods to indicate autoprocessing pipelines (EDNAProc, Dials, etc). These names are displayed in the processing widget.
3. added beamstop property. Several methods require beamstop parameters and it is convenient to access it via beamline object (and not via diffractometer hwobj)
- DozorOnlineProcessing.py: fixed method name
- ExporterMotor: renamed self.motor_position to self.chan_motor_position and self.motor_state to self.chan_motor_state. I would encourige people to use prefix chan_ and cmd_ to indicate if variable is channel or method. Otherwise it looks like variable describing position and state.
- ExporterNState: changed value validation. To be discussed.
- GenericDiffractometer: added force_emit_signals method
- QtGraphicsLib: fixed bug if qt5 is used
- VimbaVideo.py: rewrote hwobj to be compatible with the latest pymba library
- AbstractBeam: init beam size defined by the beam definer
- AbstractCollect, AbstractDetector: cleaned up the binning_mode (stored in ispyb)
- AbstractEnergy: added get_undulators_gap method
- AbstractShutter: added is_open, is_closed, open, close methods
- queue_model_objects: get container (puck) code and add it to the display name

I will create a corresponding PR in mxcubeqt after merging this PR.

2021-08-16 16:25 UTC, rhfogh commented on mxcubecore/HardwareObjects/DozorOnlineProcessing.py
> +        pixel_size = HWR.beamline.detector.get_pixel_size()
Probably fine - I do not understand Dozor. But it makes me wonder a little, since AbstractDetector.get_pixel_size is supposed to return a pair of floats (pixel size in mm), whereas setPixelMin and setPixelMax seem to take some kind of integer sa input. Are we OK here?

2021-08-16 16:27 UTC, rhfogh approved these changes
Looks good. Just one minor niggle (see relevant comment)

2021-08-16 17:24 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/DozorOnlineProcessing.py
> +        pixel_size = HWR.beamline.detector.get_pixel_size()
Yes, your are right. get_pixel_size returns a list and setPixelMin, setPixelMax requires an integer as an input. The code is ok, ... or I do not see the issue?

2021-08-17 09:04 UTC, rhfogh commented on mxcubecore/HardwareObjects/DozorOnlineProcessing.py
> +        pixel_size = HWR.beamline.detector.get_pixel_size()
One of us is missing something. The pixel size in mm is two floats between 0 and 1. I cannot see how you can meaningfully transfer that to two integers pixelMin and pixelMax. If you were talking about the *number* of pixels I could just about see it - but (by the definition of get_pixel_size) you are not.

2021-08-17 12:31 UTC, beteva requested changes

2021-08-17 12:31 UTC, beteva commented on mxcubecore/HardwareObjects/Beamline.py
> +
We should revise the roles in the Beamline object before including this one together with other 19 files in a single PR. Please remove this part from the PR

2021-08-17 12:31 UTC, beteva commented on mxcubecore/HardwareObjects/ExporterMotor.py
> +        self.chan_motor_state = None
Could you, please, tell us the reason to change the names of the variables?

2021-08-17 12:31 UTC, beteva commented on mxcubecore/HardwareObjects/ExporterNState.py
> +
Sorry, I do not get the difference between the AbstractActuator update_value, which handles value=None ant this implementation. Do you want to force the reading anyhow?

2021-08-17 12:31 UTC, beteva commented on mxcubecore/HardwareObjects/ExporterNState.py
> +
Could you, please, explain why the AbstractNState validate_value is not good? In your case you change the type of the value parameter, which makes it inconsistent with the AbstractNState.

2021-08-17 12:31 UTC, beteva commented on mxcubecore/HardwareObjects/abstract/AbstractCollect.py
> +        return HWR.beamline.energy.get_undulator_gaps()
Is it really under energy HO?

2021-08-17 12:31 UTC, beteva commented on mxcubecore/HardwareObjects/abstract/AbstractEnergy.py
> +        self.undulator_gaps = ()
I do not think the place is here. Again before doing such changes, a consensus should be achieved. Please, remove this part from your PR.

2021-08-17 12:38 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/ExporterMotor.py
> +        self.chan_motor_state = None
Hi @beteva 

See my first comment for reason. I do not think self.motor_position describes a channel and a name self.chan_motor_position is more descriptive.

2021-08-17 12:42 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/abstract/AbstractEnergy.py
> +        self.undulator_gaps = ()
Hmm, which is then a better place? Machine info?

2021-08-17 12:56 UTC, beteva commented on mxcubecore/HardwareObjects/ExporterMotor.py
> +        self.chan_motor_state = None
Sorry @IvarsKarpics, I've missed you first comment.

2021-08-17 12:59 UTC, beteva commented on mxcubecore/HardwareObjects/abstract/AbstractEnergy.py
> +        self.undulator_gaps = ()
I do not thing you need any specific place, as you may have a bending magnet, which has no gaps at all. Maybe I did not look carefully enough, but why do you need a special placeholder and not use the motors instead in your specific hardware object.

2021-08-17 13:02 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/ExporterNState.py
> +
For some reason I implemented validate_value and update_value to handle Zoom. I will check tomorrow at the beamline if it works without re implementing these methods.

2021-08-17 13:03 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/abstract/AbstractEnergy.py
> +        self.undulator_gaps = ()
The only place where those gaps are used is the ISPyBClient.py. They are stored and displayed in the ispyb gui. I think some time ago we discussed this and I do not remember why they got removed from AbstractEnergy.

2021-08-17 13:04 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/Beamline.py
> +
ok

2021-08-17 13:17 UTC, beteva commented on mxcubecore/HardwareObjects/abstract/AbstractEnergy.py
> +        self.undulator_gaps = ()
If this is of any help, we use MicrodiffZoom, which inherits from ExporterNState. It even check how many zoom levels are configured (by default 10 with the Prosilica and 6 for the B-zoom).

2021-08-18 09:15 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/DozorOnlineProcessing.py
> +        pixel_size = HWR.beamline.detector.get_pixel_size()
Hmm, indeed something went wrong here. I have not used this hwobj for a while and have to double check what this pixelMin and pixelMax represents. For sure it is not the pixel size. Can we finish this PR and I will open a new one?

2021-08-18 09:17 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/ExporterNState.py
> +
Hi @beteva  I reverted AbstractActuator and ExporterNState. For a quick look the MicrodiffZoom worked well and is sufficient.

2021-08-18 17:31 UTC, rhfogh commented on mxcubecore/HardwareObjects/DozorOnlineProcessing.py
> +        pixel_size = HWR.beamline.detector.get_pixel_size()
Sure, go ahead.

2021-08-23 14:53 UTC, beteva requested changes

2021-08-23 14:53 UTC, beteva commented on mxcubecore/HardwareObjects/abstract/AbstractDetector.py
> +        self._binning_mode = "Unbinned"
@IvarsKarpics, the get/set binning mode to take/return integer. Initialising it to a string is inconsistent.

2021-08-23 14:53 UTC, beteva commented on mxcubecore/HardwareObjects/abstract/AbstractEnergy.py
> +        self.undulator_gaps = ()
@IvarsKarpics, historically the undulator gaps were accessed in the collect hardware object. I agree, this is probably not the best place, but AbstractEnergy is not either. Could you, please, remove them from AbstractEnergy and we could decide where to implement them in another PR.

2021-08-23 14:53 UTC, beteva commented on mxcubecore/HardwareObjects/abstract/AbstractShutter.py
> +        return self.get_value() == self.VALUES.CLOSED
Would it be better to set this two as a property?

2021-08-24 07:08 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/abstract/AbstractDetector.py
> +        self._binning_mode = "Unbinned"
Hmm, maybe someone can explain me what the detectorMode in ispyb data model means? The variable is a varchar and is used in the findDetector method: https://github.com/ispyb/ISPyB/blob/66771e4bb253ad802209219ba65ec2155cc4ac77/ispyb-ejb/src/main/java/ispyb/server/mx/services/collections/Detector3ServiceBean.java#L252 that is called via webservice.

2021-08-24 07:32 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/abstract/AbstractEnergy.py
> +        self.undulator_gaps = ()
Well, I am not fully ok, but keep going I will remove the code.

2021-08-24 08:08 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/abstract/AbstractShutter.py
> +        return self.get_value() == self.VALUES.CLOSED
ok

2021-08-31 08:24 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/Beamline.py
> +        self.online_processing_methods = []
What will this list contain ?

2021-08-31 08:26 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/ExporterMotor.py
> +        self.chan_motor_position = None
IMO  `motor_position_chan` is more readable in that case (or even channel)

2021-08-31 08:29 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/QueueManager.py
> -                except Exception:
Oh, yes good :)

2021-08-31 08:31 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/abstract/AbstractBeam.py
> +            "definer": [sys.float_info.max, sys.float_info.max]
Whats the definer ?

2021-08-31 08:31 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/abstract/AbstractCollect.py
> +            detector_binning_mode=HWR.beamline.detector.get_binning_mode(),
Great :)

2021-08-31 08:34 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/abstract/AbstractDetector.py
> +        self._binning_mode = "Unbinned"
Hm, I guess we can always find a way to deal with how ISPyB wants the data its maybe more important that we are consistent with our internal `AbstractDetector`. It looks like `binning_mode` is indeed a integer in [`AbstractDetector`](
https://github.com/mxcube/mxcubecore/blob/44b8f4886faa0a0c8a14a258437ed25c4aa48dec/mxcubecore/HardwareObjects/abstract/AbstractDetector.py#L77)

2021-08-31 08:39 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/abstract/AbstractShutter.py
> +    def is_closed(self):
Do we need both is_open and is_closed ? , I guess the confusion it causes really minimal but I will for sure always need to double check when I see whichever is the least used ...

2021-08-31 09:43 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/Beamline.py
> +        self.online_processing_methods = []
list of strings. See my first comment as a descriptions of PR

2021-08-31 09:45 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/ExporterMotor.py
> +        self.chan_motor_position = None
Well, its a question of taste. I find it convenient when all channels have prefix chan and commands cmd. When there are many of them (like in diffractometer) then it is easier to read the code.

2021-08-31 09:46 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/abstract/AbstractBeam.py
> +            "definer": [sys.float_info.max, sys.float_info.max]
anything else that can change beam size and shape: crls, beamfocusing motors, etc.

2021-08-31 12:00 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/abstract/AbstractBeam.py
> +            "definer": [sys.float_info.max, sys.float_info.max]
Oh, I see interesting

2021-08-31 12:04 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/ExporterMotor.py
> +        self.chan_motor_position = None
I agree that its good to have that information in the name. As I remember it we have previously discussed this when it comes to types and that we would add a suffix i.e `list`, `dict`when it would help, for instance `something_list`. I would consider that the same reasoning should apply here. So it should then in my opinion be `motor_position_channel` or `motor_position_chan` if we would like to remain consistent.

2021-08-31 12:24 UTC, beteva commented on mxcubecore/HardwareObjects/ExporterMotor.py
> +        self.chan_motor_position = None
:+1:

2021-09-01 08:04 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/ExporterMotor.py
> +        self.chan_motor_position = None
ok, then lets have motor_position_chan

2021-09-01 08:30 UTC, beteva commented on mxcubecore/HardwareObjects/abstract/AbstractOnlineProcessing.py
> +                    HWR.beamline.beamstop.get_direction(),
Still problem with this one. Coulod you, please, remove it from this PR. We have not decided yet if the beamstop should be part of the beamline or the diffractometer, or anything else.

2021-09-01 08:33 UTC, beteva commented on mxcubecore/HardwareObjects/abstract/AbstractShutter.py
> +    def is_closed(self):
I guess is_open is enough. Closed may have more that one meaning (really closed, closed because of safety reasons...)

2021-09-01 10:51 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/abstract/AbstractOnlineProcessing.py
> +                    HWR.beamline.beamstop.get_direction(),
ok. I removed the beamstop. This method stores results in csv file and at some point we needed to store beamstop parameters. I think now it is not the case. We should definitely review beamline object.

2021-09-01 10:54 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/abstract/AbstractShutter.py
> +    def is_closed(self):
ok, I removed the is_closed method

2021-09-01 11:07 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/abstract/AbstractDetector.py
> +        self._binning_mode = "Unbinned"
For some reason this code is commented out
https://github.com/mxcube/mxcubecore/blob/b894885ee65e902769cd73ccf392c8540fffdcef/mxcubecore/HardwareObjects/ISPyBClient.py#L2193-L2205
I assume this binning_mode is never changed in mxcube. I guess if we keep it as None it will be not used as selection criteria in the ispyb web service.

2021-09-01 11:15 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/abstract/AbstractDetector.py
> +        self._binning_mode = "Unbinned"
We are in fact changing binning_mode from MXCuBE. Its not used very often at the moment, but will be used more often in the future. I cant really say way this code is commented out though (maybe due to some table update ?)

2021-09-01 11:19 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/abstract/AbstractDetector.py
> +        self._binning_mode = "Unbinned"
fine. I kept the set_ and get_ methods and set the variable to None. Lets clear this in a separate PR

2021-09-01 11:36 UTC, beteva commented on mxcubecore/HardwareObjects/abstract/AbstractOnlineProcessing.py
> +                % self.params_dict["snapshot_path"]
I like the idea of snapshot_path. Question: here you only have path, while in the previous code it was the filename. Is this for purpose.

2021-09-01 11:38 UTC, beteva approved these changes

2021-09-01 11:39 UTC, beteva commented
Side question, do we still use logging.getLogger("GUI") and what would be the difference with logging.getLogger("user_level_log")

2021-09-01 11:39 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/abstract/AbstractOnlineProcessing.py
> +                % self.params_dict["snapshot_path"]
It is just a code clean up to avoid confusion. In line 191 snapshot_path is initialized to `os.path.join(archive_directory, "snapshot.png"`

2021-09-01 11:40 UTC, IvarsKarpics commented
I personally use logging.getLogger("GUI"), because it similar to HWR and in it easier to read the log file. There is no difference between GUI and user_level_log

2021-09-01 11:55 UTC, beteva commented on mxcubecore/HardwareObjects/abstract/AbstractOnlineProcessing.py
> +                % self.params_dict["snapshot_path"]
Than it is not path, but file. The label is misleading

2021-09-13 12:53 UTC, merged