Rhfogh mxcube3
mxcube/mxcubecore pull request #648
Opened 2021-10-07 15:18 UTC by rhfogh

GPhL-specific changs, and a few bug fixes in common code.

2021-10-07 16:34 UTC, IvarsKarpics requested changes

2021-10-07 16:34 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/abstract/AbstractCollect.py
> +import sys
Is there a need for sys import?

2021-10-07 16:34 UTC, IvarsKarpics commented on mxcubecore/HardwareObjects/Gphl/GphlMessages.py
> +        self._expectedResolution = data_model.aimed_resolution
What about the variable naming. This looks like a combination of snake and camel cases. Could it be just in snake case?

2021-10-07 17:55 UTC, rhfogh commented on mxcubecore/HardwareObjects/abstract/AbstractCollect.py
> +import sys
There is  call to sys somewhere in error handling lower down

2021-10-08 09:09 UTC, beteva commented on mxcubecore/HardwareObjects/GphlWorkflow.py
> +                "Selected iudexing solution", useline
iudexing?

2021-10-08 09:14 UTC, beteva commented on mxcubecore/HardwareObjects/GphlWorkflow.py
> +            if data_model.automation_mode == "MASSIF1":
Has MASSIF1 become a common noun? 😃

2021-10-08 14:46 UTC, merged