Some updates after move to mxcubecore
mxcube/mxcubecore pull request #716
Opened 2022-10-14 07:43 UTC by marcus-oscarsson

Some fixes we made after the move to mxcubecore. No major improvements or changes but makes things work nicely has a whole :). This PR relies on #714, so the imports to queue_entry and models are changed meaning that the tests will fail until its been merged/rebased with #714.

2022-10-17 14:04 UTC, beteva approved these changes
Thank you @marcus-oscarsson for this PR - not only the new functionalities, but also effort to clean the rest.
The PR still uses Microdiff and GenericDiffractometer, which need to be replaced by AbstractDiffractometer and MicroDiffarctoemeter shortly.

2022-10-17 14:04 UTC, beteva commented on mxcubecore/BaseHardwareObjects.py
> +        """ "'public' post-initialization method. Override as needed
Maybe one " less

2022-10-17 14:04 UTC, beteva commented on mxcubecore/HardwareObjects/LimaJungfrauDetector.py
> +MaskDir = '/data/id29/inhouse/opid291/Jungfrau/tests/ahoms/processing/20220928'
Hardcoded. Either it is configurable or move the Hardware object to the  ESRF directory.

2022-10-17 17:47 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/LimaJungfrauDetector.py
> +MaskDir = '/data/id29/inhouse/opid291/Jungfrau/tests/ahoms/processing/20220928'
Oh, yes. This seems to have snuck in without me noticing ....

2022-11-02 13:55 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/NanoDiff.py
> +                self.beam_position[0] - self.zoom_centre["x"]
I assume this is black. It looks horrible.

2022-11-02 14:03 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/DESY/NanoDiff.py
> +                self.beam_position[0] - self.zoom_centre["x"]
It is indeed black, not sure its easy to change the rules for how code is split between lines. We should probably not use Black if we don't like it I guess ?

2022-11-02 14:06 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/DESY/NanoDiff.py
> +                self.beam_position[0] - self.zoom_centre["x"]
I do agree that it does not look very nice but I think we should continue to use Black. I guess the best thing in these cases is to rewrite the code a bit so that it becomes easier to read when split over several lines.

2022-11-02 14:08 UTC, rhfogh commented on mxcubecore/HardwareObjects/SampleView.py
> +        """Get snappshot(s)
-> snapshot

2022-11-02 14:12 UTC, rhfogh requested changes
This seems to be almost 'all-black', and it looks fine, with one exception:
Cpuld you undo the black changes in the files whose names start with 'Gphl'?
I am in the middle of a maojr refactoring, and it will be a lot of work for me to apply such omnipresent, detailed changes on code that is already heavily changed on my side. I can do my own black runs once my code stabilises.

2022-11-02 14:28 UTC, marcus-oscarsson commented
No problem, I removed the black run from the Gphl files

2022-11-02 14:37 UTC, rhfogh approved these changes
Excellent. Thanks!

2022-11-02 14:38 UTC, merged