take_snapshot instead of get_snapshot
mxcube/mxcubecore pull request #721
Opened 2022-11-08 16:51 UTC by meghdadyazdi

I think to be consistent with [sampleView hardwareObject](https://github.com/mxcube/mxcubecore/blob/develop/mxcubecore/HardwareObjects/SampleView.py#L140), we should define take_snapshot instead of get_snapshot.

2022-11-09 07:18 UTC, marcus-oscarsson commented
I have nothing against the name change per say, it is indeed more consistent. We need, however, to be a bit careful as this would be an API breaking change, so in theory we should then handle it as such.

If we would like this name change we should at least also need to make sure that all the "client" objects using this is updated as this is an AbstractClass we are modifying the API. Did you investigate in how many places in the code `get_snapshot` is used ?

2022-11-09 09:41 UTC, rhfogh requested changes
This is clearly a good idea, but like @marcus-oscarsson I think a bit more is required.
How about:
- changing also all the places where this function is called (as MO said)
- putting in a get_snapshot function that calls take_snapshot and have it raise a DeprecationWarning. Then we can get rid of it later, and meanwhile we are not breaking the API.

2022-11-09 10:04 UTC, marcus-oscarsson commented
Yes, adding the deprecation warning is a good idea. I agree that it would be necessary

2022-12-12 22:50 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/abstract/AbstractVideoDevice.py
>          """
Perhaps move the doc string to `take_snapshot` then, if we eventually will remove `get_snapshot`

2022-12-15 13:02 UTC, merged