SardanaMotor states are redefined
mxcube/mxcubecore pull request #723
Opened 2022-11-16 15:33 UTC by meghdadyazdi

States for motors defined in [AbstractMotor](https://github.com/mxcube/mxcubecore/blob/develop/mxcubecore/HardwareObjects/abstract/AbstractMotor.py#L40) is a little bit weird to me
like `<MotorStates.HOME: (<HardwareObjectState.READY: 3>, 5)>`
that `type(MotorStates.HOME.value)` is a tuple and makes it a little bit verbose to work with it. Maybe a better definition for States can be fine in [ExporterStaes](https://github.com/mxcube/mxcubecore/blob/develop/mxcubecore/Command/exporter/ExporterStates.py#L31).
On the other hand `class MotorStates(Enum)` seems suffering from lack of states.

Is there any reason to define these sates like that? Can we make it like one in `class ExporterStates(Enum)`

2022-11-22 10:48 UTC, meghdadyazdi commented
@beteva
Could you please have a look? or ping someone who is working with Sardana motors?

2022-11-22 14:15 UTC, beteva commented
Hi @meghdadyazdi. 

> States for motors defined in [AbstractMotor](https://github.com/mxcube/mxcubecore/blob/develop/mxcubecore/HardwareObjects/abstract/AbstractMotor.py#L40) is a little bit weird to me
> like `<MotorStates.HOME: (<HardwareObjectState.READY: 3>, 5)`

In mxcubecore we've implemented a concept, with two states - the generic state, shared by all the hardware objects, defined in HardwareObjectState and a specific state, which can differ between different hardware objects and fit the needs of a particular implementation. We've deliberately defined only few generic states, applicable to any type of hardware or action. In case you need more states (as for the motors), you define this in the specific states part.
Moreover, we specify which specific state is associated to which generic one, In the above line the idea is that the specific HOME state corresponds to the generic state READY  (HardwareObjectState.READY) , so you can move the motor,  but it also indicates that the switch is activated (5), in case you need this information.  5 is an arbitrary number in this case, but may correspond to a real value, returned by the specific hardware implementation.

> On the other hand `class MotorStates(Enum)` seems suffering from lack of states.
> Is there any reason to define these sates like that? Can we make it like one in `class ExporterStates(Enum)`

MotorStates is only an abstract implementation, just to give an idea how a concrete implementation can be done. What really is important is that you are accessing the generic state via self.STATES and the specific one via self.SPECIFIC_STATES. So your SPECIFIC_STATES can be MotorStates, ExporterStates, BlissMotorStates or any other enum, corresponding to your specific implementation (SardanaStates in you case). And it is not necessarily a tuple. In ExportStates we just make a conversion between the specific exporter states and the generic states, while in MotorStates this is all in one - specific to generic state (first member of the tuple) and specific state value (the second member of the tuple). This is very versatile, as the only obligation is that the state is an Enum.
The specific implementation can differ. In the case of ExporterMotor, it was more useful to define ExporterStates, used not just for the motors, but for other hardware, controlled via the exporter protocol. In the case of BlissMotor, the definition is in the HardwareObject itself.

It is up to you to see what is more convenient for Sardana -  implement wider SardanaStates or more specific SardanaMotorStates.

2022-11-22 17:23 UTC, beteva commented
@meghdadyazdi, concerning the changes you've made:
1. Sardana.py - it seems odd to me to have the door implementation in a generic file, but I cannot judge, as I am not using Sardana and am not aware of the specificities. Maybe somebody from ALBA could have a look.
2. SardanaMotor.py - my comments are only on the methods and signals generalities, not the calls Sardana:
   - what you've done in state_map looks correct 👍. This is one way to implement the specific states.
   - in the init, you are emitting deviceReady and deviceNotReady. I do not know who catches this, but something  like self.emit("stateChanged", self.motor_state,) is closer to the current standards.
   - only cosmetic, but as we've change from camelCase to snake_case, updateState should be update_state. Probably it is there for historic reasons.
   - sync_move - maybe you can simply use  set_value(value, timeout=None) instead of sync_move. As a general remark, we consider the motors to be a subset of actuators. That's why there is now set_value, get_value and not move any more.
   - There is a missing self._nominal_limits = (self.limit_lower, self.limit_upper) in the get_limits method. This is needed for update_limits

2022-11-28 09:35 UTC, rhfogh requested changes
Looking god. But should this PR not be rebased onto develop before it is merged?

2022-11-28 10:45 UTC, beteva requested changes

2022-11-28 10:45 UTC, beteva commented on mxcubecore/HardwareObjects/SardanaMotor.py
> +        return self.is_ready() and self.get_state() == SardanaMotorState.MOVING
Attention, get_state should return one of the standard HardwareObjectState members (self.motor_state.value). If more needed, one should implement get_specific_state as well.
Than here ther test would be either
`self.get_state() == HardwareObjectState.BUSY ` or
`self.get_specific_state() == SardanaMotorState.MOVING`

2022-12-14 12:13 UTC, rhfogh approved these changes
Looks fine to me

2022-12-15 13:58 UTC, beteva approved these changes

2022-12-15 13:58 UTC, beteva commented on mxcubecore/HardwareObjects/SardanaMotor.py
> +        HardwareObject.__init__(self, name)
Maybe you can simply replace the 2 lines by super().__init__(name)

2022-12-15 14:03 UTC, merged