[WIP] Fixes and additions done on ID29 and A1
mxcube/mxcubecore pull request #760
Opened 2023-05-26 09:14 UTC by marcus-oscarsson

- Data collections and fixes done on ID29 for SSX experiments
 - Adapted to latest workflow code GPHL and ESRF for A1
 - General bug fixes

2023-05-31 08:23 UTC, rhfogh commented on mxcubecore/HardwareObjects/ESRF/queue_entry/ssx_injector_collection.py
> +        MAX_FREQ = 925.0
On general principles, a configuration constant like this should not be defined inside a function, but in a configuration file - or failing that at module or at least class level.

2023-05-31 08:27 UTC, rhfogh commented on mxcubecore/HardwareObjects/PyISPyBClient.py
> +                "detector_distance": 177.70,
How do you justify putting hardwired constants inside a function that is named get_current_beamline_values - and that is not site-specific?

2023-05-31 08:32 UTC, rhfogh commented on mxcubecore/HardwareObjects/PyISPyBClient.py
> +    def get_additional_lims_values(self):
For this runction too - why hardwired values, and why such a generic name if only needed in a special case?

2023-05-31 08:40 UTC, rhfogh commented on mxcubecore/HardwareObjects/mockup/MotorMockup.py
> +        global DEFAULT_VALUE
Surely this is unnecessary, given that the default value is already handled elseqhere?

2023-05-31 08:44 UTC, rhfogh commented on mxcubecore/utils/conversion.py
> -HC_OVER_E = h * c / e * 1.0e7
Do you mind keeping this at 1.0e7? the values is the same as 10e6, but I think the latter is confusing - It tripped me up once already.

2023-05-31 08:45 UTC, rhfogh requested changes
The sooner this is merged the better - even if it is still WIP it would make it a lot easier for me to make subsequent PRs if this was in. Just a few  points raised that I( think would merit a look or at least a comment first.

2023-06-01 08:39 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/PyISPyBClient.py
> +                "detector_distance": 177.70,
None other really except from that its WIP and I did not yet go over that bit. I've moved the values to either configuration or reading of hardware. At the moment the PyISPyBClient have only been used on ID29 were we for instance did not have a motorized detector so it was simply easier to hard coded this value, anyways ...

The intent with this method is otherwise to create something from where we can get all those values that we somehow use together, quite often,  but that comes from various places. Thus the name `get_current_beamline_values`, I though it could be moved to some more appropriate place like the `Beamline` object  in the future but as its still a bit of work in progress.

2023-06-01 08:48 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/mockup/MotorMockup.py
> +        global DEFAULT_VALUE
Not really, as `DEFAULT_VALUE` is defined on module level above. We need to do something like this if we still want to use "predefined" mock value and also be compatible with the  `default_value` property of AbstractActuator. I could simply removed the `DEFAULT_VALUE` above, if that is what you mean ?

2023-06-01 08:50 UTC, marcus-oscarsson commented on mxcubecore/utils/conversion.py
> -HC_OVER_E = h * c / e * 1.0e7
Yes, but then we need to correct the comment "because the unit is A, not nm."  because the comment and the code is not consistent. `HC_OVER_E` is still in Angstrom

2023-06-01 09:17 UTC, rhfogh commented on mxcubecore/utils/conversion.py
> -HC_OVER_E = h * c / e * 1.0e7
Indeed, the comment is obsolete - and wrong besides. I put it in as part of a fix back when I had not understood what was happening. By all means let's remove it.

2023-06-01 09:19 UTC, rhfogh commented on mxcubecore/HardwareObjects/PyISPyBClient.py
> +                "detector_distance": 177.70,
All makes sense

2023-06-01 09:25 UTC, rhfogh commented on mxcubecore/HardwareObjects/mockup/MotorMockup.py
> +        global DEFAULT_VALUE
Id say that we do not need either the 'global' declaration or the resetting. As I understand it, self.default_value is set in a superclass init. If that is not done, self.default_value will be reset to DEFAULT_VALUE by the code as it was:
        if self.default_value is None:
            self.default_value = DEFAULT_VALUE
            self.update_value(DEFAULT_VALUE)
Again as I understand it, you only need 'global' if you want to *modiify* the module value locally.
And resetting DEFAULT_VALUE would have the effect of  resetting the module level default to the configured default_value of the first mock motor to have one. Which seems to me to be not only unnecessary but wrong. We do not want to change teh moduile level default value at all, AFAICS.

2023-06-01 09:36 UTC, rhfogh commented on mxcubecore/HardwareObjects/Microdiff.py
> +        self._wait_ready(900)  # timeout of 30 min
No real problem here - but is 900s not equal to 30min?

2023-06-01 09:40 UTC, rhfogh commented on mxcubecore/HardwareObjects/PyISPyBClient.py
> +                "detector_id": 83,
Ideally that should be in configuration and not hardwired in.

2023-06-01 09:44 UTC, rhfogh approved these changes
Nice and welcome work. Please deal with remaining comment in what you think is the best way, and then you are welcome to merge

2023-06-01 12:01 UTC, merged

2023-06-01 13:18 UTC, rhfogh commented
Thanks!

On 01/06/2023 13:01, Marcus Oscarsson wrote:
> Merged #760 <https://github.com/mxcube/mxcubecore/pull/760> into develop.
> 
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/mxcube/mxcubecore/pull/760#event-9402399106>, or 
> unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ACK5QEH3QWPT76XDAZ4JTS3XJCACLANCNFSM6AAAAAAYP6S7TE>.
> You are receiving this because you commented.Message ID: 
> ***@***.***>
>