P11 Hardware Objects update
mxcube/mxcubecore pull request #780
Opened 2023-08-25 09:19 UTC by agruzinov

Here is first part of cumulative update from P11 (DESY). This one contains (almost) only changes in HO/DESY/ after rebasing (develop branch).

Following commits have the additional logging added to /mxcubecore/mxcubecore/HardwareObjects/GenericDiffractometer.py

23c0e9db97b4473bc8980ffb843b413d04e6c1a3
f2eea9dfe9fc43e9d7e1b0957215f1840cf0b4a1

Best,
Andrey

2023-08-25 13:16 UTC, rhfogh requested changes
That is all I can give for now. I'll be looking at future PRs a well.

2023-08-25 13:16 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11AlbulaView.py
> +        if parent is not None and hasattr(parent, "eigerThread"):
Looks like 'parent' is not defined here

2023-08-25 13:16 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11AlbulaView.py
> +        super(LiveView, self).start()
Looks like Liveview is not defined here

2023-08-25 13:16 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +            raise BaseException("Cannot set prepare collection . Aborting")
Accorsding to Python docs you should never raise BaseException directly - it is an ancestor base class. I think you should never test for it directly either (use 'except:' instead) though I see it is done various places in the code.

Anyway, I'd say the exception to raise here is RuntimeError. Using 'Exception' would still be wrong, but BaseException is wronger.

There are half a dozen of these in this file.

2023-08-25 13:16 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +            g = h5fd.create_group("entry/source")
The documentation guide lines frown on parameter names shorter than three letter - but this is of course not that important.

2023-08-25 13:16 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +    def prepare_std_collection(self, start_angle, img_range):
prepare_std_collection and prepare_characterisation are identical.  If this is intended, maybe do
prepare_characterisation = prepare_std_collection 
to make it clear, or have one call the other??

2023-08-25 13:16 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +                # AG: Create screening_001, etc the same way as for CC in case of characterisation
Lines 164-184 are identical to lines 187-209

2023-08-25 13:16 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +            g = h5fd.create_group("entry/source")
Lines 433-439 and 445-453 seem to be identical

2023-08-25 13:16 UTC, rhfogh commented on mxcubecore/HardwareObjects/MotorsNPosition.py
> +    def get_properties(self, position_index, property_name):
This overrides the function of the same name in HardwareObjectNode but has a different signature (and purpose). You would have to giver it a different name to avoid clashes.

2023-08-25 13:16 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11AlbulaView.py
> +            wavelength = 12398.4 / energy
'energy' is not defined at this point for the first iteration. Move down into the try statement?

2023-08-25 13:16 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11AlbulaView.py
> +        if interval is not None:
'interval' may not eb defined here. Initialise to None at the top?

2023-08-25 13:16 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11AlbulaView.py
> +                img.optionalData().set_pixel_mask(mask_16m)
mask_16m not defined. Should it be self.mask_16m?
Same for mask_4m below

2023-08-25 13:16 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/MjpgStreamVideo.py
Just before here, 
self.sensor_dimensions = (sensor_width, sensor_height)
will break down when sensor_info is not set.

2023-08-25 13:16 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/MjpgStreamVideo.py
>              #    qimage.setNumColors(0)
take_snapshot function signature is incompatible with superclass take_snapshot function (in AbstractVideoDevice)

2023-08-25 13:16 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11EigerDetector.py
> +class P11EigerDetector(AbstractDetector):
Missing prepare_acquisition function (defined as abstract in AbstractDetector)

2023-08-25 13:16 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11SampleChanger.py
> +            raise BaseException("There is no sample to wash")
Should raise RuntimeError, not BaseException

2023-08-25 13:16 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11Session.py
> +PATH_BEAMTIME = "/gpfs/beamtime"
You shoudl peobably remove one of the PATH_BEAMTIME lines

2023-08-28 12:09 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +    def prepare_std_collection(self, start_angle, img_range):
It has become the same after several rounds of testing. I suspect it might change after further testing (it is not i the "normal" production yet). I would keep it separate for now.

2023-08-28 12:12 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +            g = h5fd.create_group("entry/source")
sorry, could not locate that so far...

2023-08-28 12:16 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11AlbulaView.py
> +        if parent is not None and hasattr(parent, "eigerThread"):
P11AlbulaView.py is anyway WIP, so it is not used yet and there are probably inconsistencies. It needs to be improved. I wanted to add it already for safekeeping . Thanks!

2023-08-28 13:46 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +    def prepare_std_collection(self, start_angle, img_range):
Makes perfect sense.

2023-08-28 13:50 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +            g = h5fd.create_group("entry/source")
In the code I checked out it is in P11Collect.add_h5_info, at the start of the try statement.  The seven lines between 
            g = h5fd.create_group("entry/source")
and
            g.attrs["NX_class"] = np.array("NXattenuator", dtype="S")
are repeated just 6 lines lower down, just with a couple of additional newlines interspersed.

2023-08-28 14:36 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/MjpgStreamVideo.py
>              #    qimage.setNumColors(0)
Thanks for noticing. Apparently, it is/was used in the previous implementation of NanoDiff.py I can not find any other instance. Probably deprecated with this signature?  Changed anyway.

2023-08-28 15:07 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11EigerDetector.py
> +class P11EigerDetector(AbstractDetector):
Actual preparation are happening elsewhere. I've added a rudimentary implementation for now.

2023-08-28 15:15 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +            g = h5fd.create_group("entry/source")
got it, thanks!

2023-08-28 15:53 UTC, rhfogh requested changes
Looks good.

Just one point:

I think that e.g. 
                    except RuntimeError():
is incoeectt, and that instead you should use 
                    except RuntimeError:

i.e. remove the parantheses give the class, not an instantiation of it.
I do not know for certain if this will break, but I have never seen the parantheses in that location.

Otherwise feel free to merge (so the next PR can start from a clean slate).

2023-08-28 16:31 UTC, agruzinov commented
Thanks for looking into that! I've also added the info from py_file_header.txt to the headers. I guess it fine for now?

2023-08-28 16:51 UTC, rhfogh requested changes
This is excellent.

Just one more thing: I would change the copyright text so it said '2010-2023' instead of '2010-2020', just so it is up to date. 

And with that you can merge it without further review..

2023-08-29 07:58 UTC, marcus-oscarsson commented
Thanks !

2023-08-29 07:59 UTC, merged