P11 update 2 - Separate set of changes to some general files
mxcube/mxcubecore pull request #782
Opened 2023-08-29 13:08 UTC by agruzinov

Here is another part of P11 files and additional cherry-picking on the P11-related HO as a part of cumulative update from work on P11 with Bixente and Jan. 

There were also couple of commits on queue_entry.py, like disabling the wait for a result from EDNA because it is not fully implemented yet. Where it could be placed? Should there be separate entry for the queue entry implementation on P11?

For example:

  collection_plan = strategy_result.getCollectionPlan()
            else:
                collection_plan = None
            log.debug("collection plan is %s. IGNORD FOR NOW" % str(collection_plan))

            # if collection_plan:
            if False:
                if char.auto_add_diff_plan:
                    # default action
                    self.handle_diffraction_plan(self.edna_result, None)

Thanks!

Andrey

2023-08-29 17:44 UTC, rhfogh commented on mxcubecore/Command/Tango.py
> +        if isinstance(value, numpy.ndarray):
'value=value' is perfectly OK, but a no-op. ONe could jsut check for tuple and NOtInitialised and otherwise do nothing.

2023-08-29 17:57 UTC, rhfogh commented on mxcubecore/Command/Tango.py
> +            if any(value != self.value):
I suspect that this will not work. I tested, and any(ndarray1 != ndarray2)  gives an error.
(ndarray1 != ndarray).any()  gives a boolean, at least, but then (4 == ndarray1).any() also gives a boolean.

Numpy arrays have effective broken Python comparison, list membership etc., so if you have to have values that are numpy arrays you need to be exceedingly careful how you handle them. Nested lists might be easier.

2023-08-29 18:01 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11Session.py
> +            return json.loads(open(filename).read())
The second return statement never gets executed.

2023-08-29 18:05 UTC, rhfogh commented on mxcubecore/HardwareObjects/TangoMotor.py
> +        if state == None:
On principle this should be 'is'. There is only one None, and '==' could trigger a __eq__ function on a state object, which coudl even return True, in theory.

2023-08-29 18:10 UTC, rhfogh commented on mxcubecore/model/queue_model_objects.py
> +        if self.get_name() != "":
Maybe consider'if self.get_name():' Which result would you want if self.get_name() returned None?

2023-08-29 18:17 UTC, rhfogh commented on mxcubecore/HardwareObjects/mockup/ShutterMockup.py
> +    def open(self):
open and close should have the same signature as the function they override. Ideally the mockup shouldhhandle timeouts as well (why can't it?), but failing that the function should at least take a timeout value, even if it does not do anything with it.

2023-08-29 18:28 UTC, rhfogh commented on mxcubecore/HardwareObjects/mockup/MotorMockup.py
> +
@beteva : Maybe we should consider adding this function to AbstractMotor?

2023-08-29 18:29 UTC, rhfogh commented on mxcubecore/HardwareObjects/mockup/BeamMockup.py
> +        self._beam_position_on_screen = [680, 512]
Should this be congfigured (eventually, not now).

2023-08-29 18:32 UTC, rhfogh commented on mxcubecore/HardwareObjects/ISPyBClient.py
> +    def is_connected(self):
This should be put in the ISPyBClient mockups as well.

2023-08-30 09:15 UTC, agruzinov commented on mxcubecore/Command/Tango.py
> +        if isinstance(value, numpy.ndarray):
I've added the changes, this might also fix the sometimes happenning infinite loop error. Some testing will be needed.

2023-08-30 10:06 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11EDNACharacterisation.py
> +        super(EDNACharacterisation, self).__init__(name)
EDNACharactersation is not defined and is not one of the superclasses.
Also you just need super() with the newer syntax.
Actually it might be easier if you did make this a subclass of EDNACharactersation, since there is a lot of duplication between those classes. But As this is WIP, I gather, this need not hold up the merge.

2023-08-30 10:19 UTC, rhfogh commented on mxcubecore/Command/Tango.py
> +        if isinstance(value, numpy.ndarray):
I had in mind something more like

       lif value == Poller.NotInitializedValue:
            value = self.get_value()
        elif isinstance(value, tuple):
            value = list(value)

There is no point in setting value = value - it does nothing.
A different point is that having a value that is a numpy array is a high bug risk because those behave in such strange ways.  If you need it you must do the necessary checking, of course, but it woudl be easier to have teh value as a list or tuple (lisat, being mutable, have their own problems when they are exported)

2023-08-30 10:19 UTC, rhfogh requested changes
So far so good.

2023-08-30 10:31 UTC, agruzinov commented on mxcubecore/Command/Tango.py
> +            if any(value != self.value):
Thanks for noticing that!

2023-08-30 11:04 UTC, rhfogh commented on mxcubecore/Command/Tango.py
> +            if (value != self.value).any():
This will work.

But, because of the peculiar behaviour of numpy the following all return True:

(numpy.zeros((3,2)) == numpy.array((0,0,0))).any()

(0 == numpy.zeros((3,2)) ).any()

If you use numpy arrays as values, you need to manually ensure that you will not get into problems with this.

2023-08-30 12:40 UTC, agruzinov commented on mxcubecore/Command/Tango.py
> +            if (value != self.value).any():
I've added check using numpy.array_equal(value, self.value). This seems to work better.

2023-08-30 13:12 UTC, agruzinov commented on mxcubecore/model/queue_model_objects.py
> +        if self.get_name() != "":
I've added the change, but maybe checking explicitly against empty string was intentional. If None, it should return default prefix.

2023-08-30 13:35 UTC, rhfogh commented on mxcubecore/Command/Tango.py
> +            if (value != self.value).any():
That is neat. I did not realise one could do that.

2023-08-30 13:56 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11EDNACharacterisation.py
> +        super(EDNACharacterisation, self).__init__(name)
I wanted to do it anyway and now it is a good excuse :) Thanks!

2023-08-30 14:49 UTC, rhfogh commented on mxcubecore/Command/Tango.py
> +            elif value != self.value:
I think these last two lines should be de-indented. It si if value is not a numpy array that you want to do the value != self.value check, right?

2023-08-30 14:50 UTC, rhfogh commented on mxcubecore/Command/Tango.py
> +        if isinstance(value, numpy.ndarray):
You could do this as an elif to the previous if statement, but this of course works equally well. Anyway, the whole is a nice solution to the numpy problem.

2023-08-30 14:59 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11Session.py
> +
I still think this one is wrong
read_info reads into the variable 'buf' and does nothing with it.
Meanwhile load_info starts with a variable called 'buf' that has not been initialised
It looks like read_info and load_info should be combined into a single function, that should be used instead of both (with whichever name you prefer)

2023-08-30 15:07 UTC, rhfogh commented on mxcubecore/HardwareObjects/mockup/ShutterMockup.py
> +    def open(self, timeout=0):
These functions should be unnecessary - they are identical to the functions in the superclass. You could just remove them

Also there seems to be a typo: it should be 
    def close(self, timeout=0):
not
    def close(self, open(self, timeout=0)):

2023-08-30 16:20 UTC, agruzinov commented on mxcubecore/Command/Tango.py
> +            elif value != self.value:
Yes! I was too fast. Thanks!

2023-08-30 16:20 UTC, agruzinov commented on mxcubecore/Command/Tango.py
> +        if isinstance(value, numpy.ndarray):
Good point. Modified.

2023-08-30 16:21 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Session.py
> +
Agree, a new combined function is added.

2023-08-30 16:49 UTC, agruzinov commented on mxcubecore/HardwareObjects/mockup/ShutterMockup.py
> +    def open(self, timeout=0):
I've lost a bit. The commit here 119fee4b6fc7268d974934443b13016f1feceda6 looks different from the current version in the dev branch. Maybe I should just revert the changes and live the last version. I guess those changes has been made originally to simulate the shutter at the beginning.

2023-08-30 16:50 UTC, agruzinov commented on mxcubecore/HardwareObjects/mockup/ShutterMockup.py
> +    def open(self, timeout=0):
sorry, in this commit: d8189637212ba14ce6dfb01705436a71ca513793

2023-08-30 17:13 UTC, rhfogh approved these changes
Guess we are there

2023-08-30 17:29 UTC, agruzinov commented
Thanks for all suggestions!

2023-08-31 14:14 UTC, beteva requested changes

2023-08-31 14:14 UTC, beteva commented on mxcubecore/HardwareObjects/abstract/AbstractShutter.py
> +
Looks like you have some old version of the shutter, which wants to put back things which have been removed or added for the AbstractShutter.py and ShutterMockup.py

2023-08-31 14:14 UTC, beteva commented on mxcubecore/HardwareObjects/mockup/ShutterMockup.py
> -        """Add additional, known in advance states to VALUES"""
Looks like you have some old version of the shutter, which wants to put back things which have been removed or added for the AbstractShutter.py and ShutterMockup.py

2023-08-31 14:16 UTC, beteva commented on mxcubecore/HardwareObjects/mockup/ShutterMockup.py
> -        """Add additional, known in advance states to VALUES"""
@agruzinov This has been changed in PR#774, merged on 19/07. Coulkd you. please, make sure that AbstractShutter and ShutterMockup in your PR are up to date.

2023-08-31 15:12 UTC, agruzinov commented on mxcubecore/HardwareObjects/mockup/ShutterMockup.py
> -        """Add additional, known in advance states to VALUES"""
Thanks for noticing that. I was synching with the develop branch, something went wrong on the rebase maybe.

2023-08-31 15:24 UTC, beteva approved these changes

2023-08-31 15:40 UTC, beteva commented
@agruzinov thanks for updating the Tango part.

2023-09-04 08:11 UTC, agruzinov commented
Main contributions came from Bixente and Jan. I've jumped in later :) Hopefully, it can be merged soon.

2023-09-04 08:42 UTC, rhfogh commented
I'd say you could merge it now, if you want - both Antonia and I have OK'ed it. Unless you think that Marcus has to express himself as well?

2023-09-06 07:27 UTC, marcus-oscarsson commented
Looks good :)

2023-09-06 07:27 UTC, merged