[WIP] MASIF-1 Cristal Direct Harvester implementation
mxcube/mxcubecore pull request #826
Opened 2023-12-06 14:55 UTC by jbflo

This is the code related to the implementation of the Cristal Direct Harvester in Massif-1 ESRF

This should not have breaking change. 
Beamline who does not have an Harvester should not have any new things/modification to do 
A PR in Mxcube-web related to this one need to be reviewed as well .

2023-12-06 16:20 UTC, fabcor-maxiv reviewed
A couple of random comments. I did not review the whole thing, we do not seem to have such harvester.

2023-12-06 16:20 UTC, fabcor-maxiv commented on mxcubecore/Command/exporter/ExporterClient.py
>              logging.getLogger("HWR").error(msg)
As far as I know, the recommendation for Python logging is to always use printf style formatting (the one with the `%` interpolation) to take advantage of lazy evaluation:

* https://realpython.com/python-f-strings/#lazy-evaluation-in-logging
* https://docs.python.org/3/library/stdtypes.html#old-string-formatting

2023-12-06 16:20 UTC, fabcor-maxiv commented on mxcubecore/HardwareObjects/Beamline.py
> +            Optional[AbstractHarvester]:
Why not use type hints?

2023-12-08 09:23 UTC, jbflo commented on mxcubecore/HardwareObjects/Beamline.py
> +            Optional[AbstractHarvester]:
As the other method are like this, i'll leave it  for now. maybe someone can make the change for all the methods in this class in a separate PR.

2023-12-08 10:26 UTC, beteva commented on mxcubecore/HardwareObjects/abstract/AbstractSampleChanger.py
> +    @abc.abstractmethod
I would remove the abstract decorator, as it is only specific for the harvester and should not require that all the sample changers implement this method.

2024-01-05 16:09 UTC, beteva requested changes

2024-01-05 16:09 UTC, beteva commented on mxcubecore/Command/exporter/ExporterClient.py
> +            msg = "{} : {}".format(self.get_server_object_name(), str(ret[4:]))
You might as well consider use the f-string (see with pylint).

2024-01-05 16:09 UTC, beteva commented on mxcubecore/HardwareObjects/Beamline.py
> +            Optional[AbstractHarvester]:
Is this needed? It can be just seen as a sample changer in beamline.

2024-01-05 16:09 UTC, beteva commented on mxcubecore/HardwareObjects/Beamline.py
> +    __content_roles.append("harvester_maintenance")
Is this needed? It can be just seen as a sample changer in beamline.

2024-01-05 16:09 UTC, beteva commented on mxcubecore/HardwareObjects/EMBLFlexHCD.py
> +
@jbflo, please see my comment for the AbstractSampleChanger.

2024-01-05 16:09 UTC, beteva commented on mxcubecore/HardwareObjects/EMBLFlexHCD.py
>          return present_sample_list
For better readability, it would be good to split this in three methods - the get_sample_list, which is the standard method, which calls  _get sample_list_flex and _get_sample_list_harvester.

2024-01-05 16:09 UTC, beteva commented on mxcubecore/HardwareObjects/EMBLFlexHCD.py
> +            return False
Attention, this is changing the behaviour of the method.

2024-01-05 16:09 UTC, beteva commented on mxcubecore/HardwareObjects/Harvester.py
> +"""
It is great that there is some explanation, Could you, please, add the standard MXCuBE license message (see EMBLFlexHCD.py) Also the xml example should use object instead of equipment.

2024-01-05 16:09 UTC, beteva commented on mxcubecore/HardwareObjects/HarvesterMaintenance.py
> +"""
Same as for Harvester.

2024-01-05 16:09 UTC, beteva commented on mxcubecore/HardwareObjects/abstract/AbstractSampleChanger.py
> +
Is this used to check if harvester or sample changer is used? If yes, than the name is misleading (maybe something like is_harvester is more appropriated) and moreover it should be a property.

2024-01-08 12:33 UTC, jbflo commented on mxcubecore/Command/exporter/ExporterClient.py
> +            msg = "{} : {}".format(self.get_server_object_name(), str(ret[4:]))
I did, but then followed Fabcor suggestion 
https://github.com/mxcube/mxcubecore/pull/826#discussion_r1417609839

2024-01-11 17:26 UTC, jbflo commented on mxcubecore/HardwareObjects/Beamline.py
> +            Optional[AbstractHarvester]:
Yes, yes but it is a bit more complex.
- This Hardware can not be treated as a sample changer as it is more like a sample Holder. 
-Accessing it is possible through the Sample Changer but In Massif-1 they still wanted to use the Harvester even the Sample Changer is not available.

2024-01-11 17:26 UTC, jbflo commented on mxcubecore/HardwareObjects/Beamline.py
> +    __content_roles.append("harvester_maintenance")
https://github.com/mxcube/mxcubecore/pull/826#discussion_r1449178378

2024-01-12 09:09 UTC, beteva commented on mxcubecore/HardwareObjects/Beamline.py
> +            Optional[AbstractHarvester]:
My question was more can't you specify the harvester hardware object instead of the sample changer in the beamline configuration. Thus you can also benefit from the checks which are done for mounting/unmounting.

2024-01-15 12:13 UTC, jbflo commented on mxcubecore/HardwareObjects/EMBLFlexHCD.py
> +            return False
Yes,  We have to see on Other Beamlines, but in Massif-1 this behavoir is OK in since
Just raise will return None which consider a loading success.
But to avoid  to collect on the previous mounted sample.  a return False fit better.

2024-01-15 12:45 UTC, rhfogh commented on mxcubecore/HardwareObjects/EMBLFlexHCD.py
> +            return False
I would not agree here, J-B. The behaviour of load (which is determined by _do_load) must be the same as the behaviour of SampleChanger.load(). Replacing a raised error with a return of False does nto look like teh same behaviour.

2024-01-15 12:47 UTC, rhfogh requested changes
Surely a file called EMBLFlexHCD.py should be in HardwareObjects/EMBL, and not in HardwareObjects/ ?

2024-01-15 18:23 UTC, beteva commented
Not quite @rhfogh, in this case it refers that the flex is manifactured by EMBL, just as Cats, Marvin ...:-)

2024-01-15 18:25 UTC, rhfogh commented on mxcubecore/HardwareObjects/Beamline.py
> +            Optional[AbstractHarvester]:
Ah well, in that case it should stay where it is. I do not seem to have a very high hit-rate today )-:

2024-01-16 15:29 UTC, jbflo commented on mxcubecore/HardwareObjects/EMBLFlexHCD.py
> +            return False
not only   MASSIF-1,  I mentioned Massif-1 because it's there I found the issue. 
this code bellow is not quite OK  ? why if load return None , you make it True ?
https://github.com/mxcube/mxcubeweb/blob/a958e7d1d3e4ffcc354974d07685522088f7cd23/mxcubeweb/core/components/samplechanger.py#L198C1-L205C31

2024-01-16 16:30 UTC, rhfogh commented on mxcubecore/HardwareObjects/EMBLFlexHCD.py
> +            return False
I'd say the problem is that happens if load raises an error. The way this would normally work in Python, the raised error would stop further execution of the code and jump right down to line 224 where it says:

        except Exception as ex:
            logging.getLogger("MX3.HWR").exception("[SC] sample could not be mounted")
            raise RuntimeError(str(ex)) from ex

Since this again raises an error, you would never get to line 244 
        return res
but would have the error propagate upwards to the next error handler. 
With your change you would get a different behaviour: you would have the function return False instead of raising an error. If you are making that change I would say you need  a very careful analysis of the calling functions and their error handling to be sure that you want the new behaviour rather than the old one.

2024-02-26 10:05 UTC, jbflo commented on mxcubecore/HardwareObjects/EMBLFlexHCD.py
> +
method removed from AbstractSampleChanger

2024-03-26 12:05 UTC, jbflo commented
> Surely a file called EMBLFlexHCD.py should be in HardwareObjects/EMBL, and not in HardwareObjects/ ?

@rhfogh  Are you still request this change  ?

2024-03-26 12:07 UTC, jbflo commented on mxcubecore/HardwareObjects/Beamline.py
> +            Optional[AbstractHarvester]:
> Is this needed? It can be just seen as a sample changer in beamline.

@beteva  As we discuss a while ago, could you have look again ?

2024-03-26 13:26 UTC, rhfogh approved these changes

2024-04-03 14:55 UTC, marcus-oscarsson approved these changes

2024-04-03 14:56 UTC, marcus-oscarsson commented
Looks good as far as I can see :), (its a big one ;) )

2024-04-03 15:26 UTC, beteva commented on mxcubecore/HardwareObjects/abstract/sample_changer/Crims.py
> +            'User-Agent' : "Mozilla/5.0 (Windows NT 6.1; Win64; x64",
Should this really be hard-coded?

2024-04-03 15:33 UTC, beteva commented
Hi @jbflo, Most of the changes are Ok with me. It still bothers me, though, that you have to check for harvester in the EMBLFlexHCD.py.

2024-04-03 15:48 UTC, jbflo commented on mxcubecore/HardwareObjects/Harvester.py
> +    def check_crystal_state(self, crystal_uuid: str) -> str | None:
@beteva @marcus-oscarsson I Just Notice  this Type type hints
require Python 1.10 and above.
Is this a problem ?

2024-04-03 15:56 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/Harvester.py
> +    def check_crystal_state(self, crystal_uuid: str) -> str | None:
You mean ` str | None` ?

2024-04-03 16:02 UTC, jbflo commented on mxcubecore/HardwareObjects/Harvester.py
> +    def check_crystal_state(self, crystal_uuid: str) -> str | None:
> You mean ` str | None` ?
Yes
> You should be able to use
> 
> ```
> from typing import Optional
>  ... -> Optional[str]
> ```
Yeah,

2024-04-03 17:22 UTC, jbflo commented
> Hi @jbflo, Most of the changes are Ok with me. It still bothers me, though, that you have to check for harvester in the EMBLFlexHCD.py. 

as we We check because depending of where the SC take the Sample , the Sample List and the Next Actions are different 

maybe it's because the Dewar is (consider) a part of the FLEX.

Now we should probably think of 2 things.
1- The Sample changer ( the Robot ) FLEX
2 The Sample Holder (Can be a Dewar(HCD) or Harvester)

Or maybe we should have a Flex and a HCD Class ?  Or an EMBLFlexHavester CLass ?
having them both implementing as one is not much help understanding the Harvester.

Yeah maybe an EMBLFlexHavester CLass but this will have must of the EMBLFlexHCD methode In.

I am thinking about it @beteva , but for now i don't have a better clue.
for now I Think this class (EMBLFlexHCD) is the best place. 

please let me know if you are thinking  of a better logic.

2024-04-04 07:53 UTC, fabcor-maxiv commented on mxcubecore/HardwareObjects/abstract/sample_changer/Crims.py
> +            + "?janitor_key=kbonvRqc8"
Maybe better as an f-string?

Also is the key supposed to be here? Is that a secret?

2024-04-10 14:14 UTC, marcus-oscarsson commented
I agree with @beteva that it would be nice if the sample changer and the Harvester code could be de-coupled. I think that would be a nice followup PR.

2024-04-10 15:22 UTC, beteva commented
> I am thinking about it @beteva , but for now i don't have a better clue. for now I Think this class (EMBLFlexHCD) is the best place.
> 
> please let me know if you are thinking of a better logic.
@jbflo, it might be tempting to split Robot and Holder, but I am afraid that this will add an extra complication to already complicated device. I would rather go for the other idea - having a specific  EMBLFlexHavester CLass, which inherits from the EMBLFlexHCD and only overloads the methods which differ for the harvester. Than in the beamlise-setup.yml it will be easy to choose which "sample changer" you have at given moment.What do you think?

2024-04-10 16:04 UTC, jbflo commented
> > I am thinking about it @beteva , but for now i don't have a better clue. for now I Think this class (EMBLFlexHCD) is the best place.
> > please let me know if you are thinking of a better logic.
> > @jbflo, it might be tempting to split Robot and Holder, but I am afraid that this will add an extra complication to already complicated device. I would rather go for the other idea - having a specific  EMBLFlexHavester CLass, which inherits from the EMBLFlexHCD and only overloads the methods which differ for the harvester. Than in the beamlise-setup.yml it will be easy to choose which "sample changer" you have at given moment.What do you think?

Yes I also think it's a better Idea , I'll go on that side. Thanks !

2024-04-10 17:35 UTC, beteva approved these changes
Well done @jbflo. All looks nice and neat. I only have few style remarks. Have not checked the EMBLFlexHCD code, but I trust you it is the original one.

2024-04-10 17:35 UTC, beteva commented on mxcubecore/HardwareObjects/EMBLFlexHarvester.py
> +        super(EMBLFlexHarvester, self).__init__(self.__TYPE__, True, *args, **kwargs)
You can do
`super().__init__(*args, **kwargs)` 
Also self._loaded_sample = (-1, -1, -1) is better to be here, than in init(). you can also add self._harvester = None (not compulsory, just style).

2024-04-10 17:35 UTC, beteva commented on mxcubecore/HardwareObjects/EMBLFlexHarvester.py
> +        return sample
get_loaded_sample() is identical to the parent class. no need to overload it

2024-04-10 17:37 UTC, beteva commented on mxcubecore/HardwareObjects/EMBLFlexHarvester.py
> +        return sample
Please, check the style with black as well.

2024-04-12 06:05 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/EMBLFlexHCD.py
> +    def get_room_temperature_mode(self):
I guess these two methods should not be here then, if we now have the `EMBLFlexHarvester` object

2024-04-15 10:04 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/Beamline.py
> +        # """)
Remove or un-comment ?

2024-04-15 10:04 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/EMBLFlexHCD.py
> -        if not -1 in sample and sample != previous_sample:
Looks good :) :+1:

2024-04-15 10:05 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/EMBLFlexHarvester.py
> +# encoding: utf-8
Looks good as far as I can see

2024-04-15 10:06 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/EMBLFlexHarvester.py
> +    def mount_from_harvester(self):
Does this mean that there should be an equivalent method for the AbstractSampleChanger that returns false by default, or how is this used ?

2024-04-15 10:10 UTC, marcus-oscarsson commented on mxcubecore/model/queue_model_objects.py
> +    def has_protein_acronym(self):
Can't we somehow merge this with has_lims_data so that we dont need to check for both here :https://github.com/mxcube/mxcubecore/pull/826/files#diff-bf4145a2e91e5b6388dbc69591ea8c2fc19b54fcdf10087cd77b0087ccb3b423R283

2024-04-15 10:12 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/Microdiff.py
> +        self.saved_motor_position = {}
How is `saved_motor_position` used ?

2024-04-15 11:24 UTC, rhfogh commented on mxcubecore/HardwareObjects/EMBLFlexHCD.py
> +        except Exception:
I think this should actually be 'except:' - whatever the linter says. 
The difference is that 'except:' also catches 'built-in system-exiting exceptions', and in this case you are re-raising the exception anyway and you  would still want to log the robot_exceptions before exiting.

2024-04-15 11:30 UTC, jbflo commented on mxcubecore/model/queue_model_objects.py
> +    def has_protein_acronym(self):
Hmm I think not . 
unfortunately  has_lims_data logic  is  not suitable for all cases. 
in this case protein acronym is known even there is no lims data .

And The scientist would ask for it again if we remove the second check.
Having the acronym as parts in the prefix was a mandatory for them.

we could maybe merge  has_protein_acronym with has_lims_data ?
 
 
 PS : thanks i should not use TypeError here i'll fix it,

2024-04-15 11:45 UTC, jbflo commented on mxcubecore/HardwareObjects/Microdiff.py
> +        self.saved_motor_position = {}
- For calibration purpose (to find find offset position )
 1 -  move those motors to a specific position and saved 
 2 - move again .. and again example(3 click centering)
 3-  then we need the saved position for offsets calculation
 
it being used here : https://github.com/mxcube/mxcubeweb/pull/1145/files#diff-5ea1dcf48d30f15039fd0b4b1bd66d2b46bc68ee3aa35f4f0db10259723ffa79R280

2024-04-15 12:04 UTC, jbflo commented on mxcubecore/HardwareObjects/EMBLFlexHCD.py
> +        except Exception:
hmm should we not care about linter anymore ?
PR should be merge if linter are passed right ?

Not an expert, i'll leave this for the other guys :smiley:

2024-04-15 12:30 UTC, jbflo commented on mxcubecore/HardwareObjects/Beamline.py
> +        # """)
I could but i Prefer not making the remove part of this PR. 

it Was already commented.
by @ Andrey Gruzinov Maybe ?
I just applied black on it so it could pass the Linter.

2024-04-15 12:41 UTC, jbflo commented on mxcubecore/HardwareObjects/EMBLFlexHarvester.py
> +    def mount_from_harvester(self):
HAHA :smiley: , Having an AbstractSampleChanger  equivalent method that returns false by default for 
mount_from_harvester is  indeed what I wanted.

but could not agree on this with @beteva 
Or maybe my explanation was not clear enough 
SO I find a work around and ending up removing it from AbstractSampleChanger.

2024-04-15 13:51 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/EMBLFlexHCD.py
> +        except Exception:
You can use `BaseException` if you want to catch 'built-in system-exiting exceptions' and still keep the linter happy. However, I don't think we should be catching those, unless there is a good reason for it, even if as in this case we re-raise them.

2024-04-15 13:53 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/Beamline.py
> +        # """)
I see, black is good but Id say commented code like this can simply be removed

2024-04-15 13:54 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/EMBLFlexHarvester.py
> +    def mount_from_harvester(self):
But how then are you using this method of the base class does not have this method any other sample changer would throw an `AttributeErrror`

2024-04-15 13:55 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/Microdiff.py
> +        self.saved_motor_position = {}
Hm, are you sure, I could not find any reference to `saved_motor_position`

2024-04-15 13:57 UTC, marcus-oscarsson commented on mxcubecore/model/queue_model_objects.py
> +    def has_protein_acronym(self):
> we could maybe merge has_protein_acronym with has_lims_data ?

yes, it that would be nice if we could try that

2024-04-15 13:58 UTC, rhfogh commented on mxcubecore/HardwareObjects/EMBLFlexHCD.py
> +        except Exception:
In this case I think there is a good reason. We want to log those accumulated messages before we exit.
Also, frankly, following the linter in this case is a matter of the tail wagging the dog. That particular linter point was put in to 'encourage' people to put in specific exceptions rather than catching everything willy-nilly. If we want to allow a bare 'except:' in some cases (and I think we do) surely we should either remover that check from the linter or use the mechanisms for making exceptions for a given line of code. Making convoluted python code to be allowed to do what we want while by passing the linter does not sound like the right way to go.

2024-04-15 14:07 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/EMBLFlexHCD.py
> +        except Exception:
Well, in this case the sample changer wont raise a system exiting exception and if it does we probably can't ask it to give us the reason for it. If it does we would know what happened by looking at the stacktrace or the sample changer log file.

The second point would be that, its really not a good idea to catch system exiting exceptions because we might trap them and our program might not exit or behave in strange ways. Its problematic when we use CTRL-C or for us more commonly decide to stop the queue by raising `GreenletExit`

2024-04-15 14:08 UTC, beteva commented on mxcubecore/HardwareObjects/EMBLFlexHarvester.py
> +    def mount_from_harvester(self):
I still do not like to have anything about harvester in the AbstractSampleChanger class. For me, unless I do not get it right, the _do_load method should be overloaded with this one.

2024-04-15 14:19 UTC, jbflo commented on mxcubecore/HardwareObjects/EMBLFlexHarvester.py
> +    def mount_from_harvester(self):
> But how then are you using this method of the base class does not have this method any other sample changer would throw an `AttributeError`

`    
       sc = HWR.beamline.sample_changer

        try:
            mount_from_harvester = sc.mount_from_harvester()
        except AttributeError:
            mount_from_harvester = False`
            
I did this way every time.  not elegant but  SC who does not this method should pass the AttributeError

2024-04-15 14:22 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/EMBLFlexHarvester.py
> +    def mount_from_harvester(self):
But, why do you need to call `mount_from_harvester` specifically would it not be enough to call `mount` and the `mount` of the `Harvester` object knows what to do ?

2024-04-15 14:38 UTC, jbflo commented on mxcubecore/HardwareObjects/Microdiff.py
> +        self.saved_motor_position = {}
> Hm, are you sure, I could not find any reference to `saved_motor_position`

Yes, Just tagged you , https://github.com/mxcube/mxcubeweb/pull/1145#discussion_r1565904742

2024-04-15 14:39 UTC, rhfogh commented on mxcubecore/HardwareObjects/EMBLFlexHCD.py
> +        except Exception:
OK, I'll take that as a convincing argument. Point withdrawn.

2024-04-15 15:14 UTC, jbflo commented on mxcubecore/HardwareObjects/EMBLFlexHarvester.py
> +    def mount_from_harvester(self):
1 there is a lot of mounting logic there : mxcubeweb/core/components/samplechanger.py  

And mount_from_harvester help us prevent or add  behavior that not or are specific when mounting from an Harvester.  
 
have a look at this PR: [https://github.com/mxcube/mxcubeweb/pull/1145/files](url)
FIle :  mxcubeweb/core/components/samplechanger.py  


PS : those two PR are a big big (Sorry about that), but reviewing them both together maybe better

2024-04-15 15:35 UTC, marcus-oscarsson commented on mxcubecore/HardwareObjects/EMBLFlexHarvester.py
> +    def mount_from_harvester(self):
I see, how about simply setting a flag on the harvester hardware object and deal with the mounting specifics in the harvester hardware object. I assume that you know precisely when you need to use harvester. You could  add something to the sample address so that you know that its a harvester sample. In this case the harvester hardware object would know if its a standard sample or a harvester sample.

2024-04-16 07:59 UTC, jbflo commented on mxcubecore/HardwareObjects/EMBLFlexHarvester.py
> +    def mount_from_harvester(self):
That will  unfortunately not enough :  mxcubeweb.mxcubeweb.core.components.samplechanger.py
has specific logic related to queuing, loading and  centering that are by default.

Things we don't want : default autoloop centring
Things we want do to : add logic while execution of queue 

it's not just mounting, have another look at  this file : [https://github.com/mxcube/mxcubeweb/blob/JB-develop-harvester/mxcubeweb/core/components/samplechanger.py](url)
check on method like queue_mount_sample or mount_sample_clean_up.

2024-04-16 10:13 UTC, jbflo commented on mxcubecore/model/queue_model_objects.py
> +    def has_protein_acronym(self):
@marcus-oscarsson I had another look and i think a merge is not a good fit for this logic.

has_lims_data method name is too generic would have been better as has_lims_id ..
has_protein_acronym is well suit on the get_default_prefix as you only wanted to care about the protein_acronym


`  i would recommend something like that : 

      if sample_data_node:
            if (sample_data_node.has_protein_acronym()):
                protein_acronym = sample_data_node.crystals[0].protein_acronym
                name = sample_data_node.name
                if name:
                    prefix = "%s-%s" % (protein_acronym, name)
                else:
                    prefix = protein_acronym
            else:
                prefix = name or ""
        elif generic_name:
            prefix = "<acronym>-<name>"
`

and not use

2024-04-17 14:26 UTC, jbflo commented on mxcubecore/HardwareObjects/Beamline.py
> +        # """)
comment removed

2024-04-26 13:41 UTC, merged