[Documentation Code Camp] docstrings for emitted signals
mxcube/mxcubecore pull request #866
Opened 2024-03-14 13:47 UTC by meguiraun

Initial work for documenting emitted signals. I initially focused  on the abstract classes (not all done yet 🤪)

Example output:
<img width="781" alt="image" src="https://github.com/mxcube/mxcubecore/assets/12758327/a0808761-8ebf-4324-aac9-bb6ad5c104a0">

2024-03-14 14:54 UTC, fabcor-maxiv commented
Wouldn't it make more sense to document the emitted signals at the class level rather than at the method level?

If I use an *actuator* I want to know what signals it emits and when (under what circumstances, i.e. what is the meaning of the signal), but I do not need to know which of the actuator's methods actually emits the signal, do I?

And same thing, if I want to implement a new (concrete) actuator, I want to know what signals my actuator should emit, but I will choose which methods will actually emit those signals.

cc @elmjag

2024-03-14 15:41 UTC, beteva commented
@meguiraun thanks for the work. Good start. There is one slight problem - I think AbstractAperture is an obsolete class, There will be very soon a new PR to handle aperture test and mock up, but they inherit from AbstractNState. In this context, would you mind if we see together which are the obsolete abstract classes.
@fabcor-maxiv I guess it is all right if we document the signals on the class level only. Actually this is the case right now, but certainly needs a bit of explanation which signal means what.

Maybe we should make a general signals documentation file, which lists all the "standard" signals, like valueChanged, limitsChanges, stateChanged, specificStateChanged, as well as the methods defined in  BaseHardwareObjects.py - the emit method (namely its signature in order to explain how to emit a signal) and the force_emit_signals method,  available for overloading . If we go for this, than we could explain the usage of these signals and in the classes only mention which are the emitted  signals,  and only document if there are other signals, specific for the class. What do you think?

2024-03-14 18:22 UTC, rhfogh commented
I agree with @beteva - The biggest need is what are the general kinds of signals that are used to tie the application together, where they come from, and what they do. In a way the biggest question is not so much 'which signals does this class emit' but 'which signals should I listen for' and 'which signals do I need to emit in my own class?'.

2024-03-18 07:28 UTC, meguiraun commented
okey, I see your point. I will leave the methods out.

yes, totally agree with a general documentation page (why, where in code are coming, some basic example, etc.), I had it in mind but I thought to start with documenting the code

2024-03-18 11:29 UTC, meguiraun commented
1. Added a new md with signal documentation, very early, please @beteva @rhfogh  have a look, and if you feel so commit any improvement
2. Updated, let me know if the "new" AbstracActuator class documentation is ok:

<img width="688" alt="image" src="https://github.com/mxcube/mxcubecore/assets/12758327/26fd8081-6f16-44f5-8861-0567efd016c1">

2024-03-18 12:16 UTC, fabcor-maxiv requested changes

2024-03-18 12:16 UTC, fabcor-maxiv commented on mxcubecore/HardwareObjects/abstract/AbstractActuator.py
> +        the number of legs the animal has (default 4)
What!? :D

```suggestion
```

2024-03-18 12:16 UTC, fabcor-maxiv commented on mxcubecore/HardwareObjects/abstract/AbstractActuator.py
> +
```suggestion
    Attributes:
        _nominal_value (float):
            Current actuator value
        default_value (float):
            value specified by XML property, otherwise `None`
        _nominal_limits (tuple):
            values specified by XML property, otherwise `None`
        actuator_name (str):
            actuator name specified by XML property, otherwise `None`
        read_only (bool):
            read only flag, specified by XML property, otherwise `False`
```

2024-03-18 12:16 UTC, fabcor-maxiv commented on mxcubecore/HardwareObjects/abstract/AbstractBeam.py
> +            beamSizeChanged:  ('beamSizeChanged', (width, height)))
```suggestion
            beamSizeChanged:  ('beamSizeChanged', (width, height))
```

2024-03-18 12:19 UTC, fabcor-maxiv commented on docs/source/dev/hwobj_signals.md
Personal preference, we do not have a policy for this as far as I know: I tend to prefer "_[Semantic Line Breaks](https://sembr.org/)_".

2024-03-18 12:23 UTC, rhfogh commented on docs/source/dev/hwobj_signals.md
Fabien only just introduced me to semantic line breaks, but I am heartily in favour.

2024-03-18 12:48 UTC, fabcor-maxiv requested changes
I do not think there is a `BaseHardwareObject` class. So I replaced with `HardwareObejct`. But in most cases what we talk about is actually in the `HardwareObjectMixin`.

I tried the Sphinx/docutils cross-reference roles, we'll see if we get better links.

In principle we should be able to configure Sphinx to keep a copy of the source code, so that we can have links to source code in the documentation (not links to GitHub).

And in general, not only for (Sphinx) documentation, we should avoid links to a branch, but use permalinks that link to a specific commit.

2024-03-18 12:48 UTC, fabcor-maxiv commented on docs/source/dev/hwobj_signals.md
> +MXCuBE relies heavily on signals beeing emmited and listened to by many elements. For example, a hardware object may listen to other lower level hardware objects in order to update values after some
```suggestion
MXCuBE relies heavily on signals being emitted and listened to by many elements. For example, a hardware object may listen to other lower level hardware objects in order to update values after some calculation. But it is also critical in the UI (both web and Qt), in both cases they expect periodic signal updates for displaying the most recent information to the user (e.g. motor positions, data collection state, etc.)
```

2024-03-18 12:48 UTC, fabcor-maxiv commented on docs/source/dev/hwobj_signals.md
> +Depending on the installed modules signals are emitted using [Louie](https://pypi.org/project/Louie/) or [PyDispatcher](https://pypi.org/project/PyDispatcher/). The former being based on the later. T
```suggestion
Depending on the installed modules, signals are emitted using [Louie](https://pypi.org/project/Louie/) or [PyDispatcher](https://pypi.org/project/PyDispatcher/). The former being based on the later. The developer does not need to deal with the differences between those two modules as it is already being handled in the file [dispatcher](https://github.com/mxcube/mxcubecore/blob/develop/mxcubecore/dispatcher.py).
```

2024-03-18 12:48 UTC, fabcor-maxiv commented on docs/source/dev/hwobj_signals.md
> + **_NOTE:_**  can we remove of of those dependencies?
```suggestion
 **_NOTE:_**  can we remove any of those dependencies?
```

2024-03-18 12:48 UTC, fabcor-maxiv commented on docs/source/dev/hwobj_signals.md
> +The [BaseHardwareObject](https://github.com/mxcube/mxcubecore/blob/develop/mxcubecore/BaseHardwareObjects.py) class serves as the base class for all hardware objects in MXCuBE. It includes methods fo
```suggestion
The :py:class:`mxcubecore.BaseHardwareObjects.HardwareObject` class serves as the base class for all hardware objects in MXCuBE. It includes methods for defining and emitting signals, allowing derived classes to customize signal emission based on their specific requirements.
```

2024-03-18 12:48 UTC, fabcor-maxiv commented on docs/source/dev/hwobj_signals.md
> +To emit a signal, derived classes can use the `emit` method provided by the BaseHardwareObject class. This method takes the name of the signal as an argument and optionally includes additional data o
```suggestion
To emit a signal, derived classes can use the :py:meth:`mxcubecore.BaseHardwareObjects.HardwareObjectMixin.emit` method provided by the :py:class:`HardwareObject` class. This method takes the name of the signal as an argument and optionally includes additional data or parameters to pass along with the signal. This method calls the `dispatcher.send` method.
```

2024-03-18 12:48 UTC, fabcor-maxiv commented on docs/source/dev/hwobj_signals.md
> +From the _BaseHardwareObject_ class (removing extra lines for brevity):
```suggestion
From the :py:class:`HardwareObject` class (removing extra lines for brevity):
```

2024-03-18 12:48 UTC, fabcor-maxiv commented on docs/source/dev/hwobj_signals.md
> +So, in a custom hardware object, since inhnerits from _BaseHardwareObject_, one only needs to call:
```suggestion
So, in a custom hardware object, since it inherits from {py:class}`HardwareObject`, one only needs to call: 
```

2024-03-18 12:48 UTC, fabcor-maxiv commented on docs/source/dev/hwobj_signals.md
> +_BaseHardwareObject_ implements the following ```connect```method, built around the homonymous method of _PyDispatcher_. Making it more convenient to use. The functions provides syntactic sugar ; Ins
```suggestion
{py:class}`HardwareObject` implements the following {py:meth}`HardwareObjectMixin.connect` method, built around the homonymous method of _PyDispatcher_. Making it more convenient to use. The functions provides syntactic sugar: instead of `self.connect(self, "signal", slot)` it is possible to do `self.connect("signal", slot)`.
```

2024-03-18 12:48 UTC, fabcor-maxiv commented on docs/source/dev/hwobj_signals.md
> +From the [BaseHardwareObject](https://github.com/mxcube/mxcubecore/blob/develop/mxcubecore/BaseHardwareObjects.py#L878) class (removing extra lines for brevity):
```suggestion
From the {py:meth}`HardwareObjectMixin.connect` method (removing extra lines for brevity):
```

2024-03-18 12:48 UTC, fabcor-maxiv commented on docs/source/dev/hwobj_signals.md
> +This assumes that ```some_other_hwobj``` is linked in the custom hwobj initialization, and _callback_method_ must exist, otherwise an exception will happen once the signal is received.
```suggestion
This assumes that `some_other_hwobj` is linked in the custom hardware object initialization, and `callback_method` must exist, otherwise an exception will happen once the signal is received.
```

2024-03-18 12:48 UTC, fabcor-maxiv commented on docs/source/dev/hwobj_signals.md
> +If the sender hwobj has a method named ```connect_notify```, it will be called on connect. Since this connect happens at application init, this typically triggers the emission of all signals during i
```suggestion
If the sender hardware object has a method named `connect_notify`, it will be called on connect. Since this connect happens at application initialization, this typically triggers the emission of all signals during initialization, and thus all receivers start with the most recent value.
```

2024-03-18 12:48 UTC, fabcor-maxiv commented on docs/source/dev/hwobj_signals.md
> +> At least one entry must appear in the beamline config yml file, in this case I left the procedure mockup, all the other mockups are commented. Thats why only a few items appear in the loading table
```suggestion
> At least one entry must appear in the beamline's YAML configuration file. In this case I left the procedure mockup only, all the other mockups are commented. That is why only a few items appear in the loading table.
```

2024-03-18 12:56 UTC, fabcor-maxiv commented
In many of the modified docstrings, it feels like adding the correct type hints would be nearly as efficient (especially for the return values).

2024-03-18 13:01 UTC, rhfogh commented
@fabcor-maxiv  HardwareObjectMixin woudl be the right choice throughout. HardwareObjects inherit from *either* HardwareObject *or* HardwareObjectYaml, but both inherit from HardwareObjectMixin,.

2024-03-18 15:03 UTC, elmjag commented on docs/source/dev/hwobj_signals.md
wait, semantic break is the same things as putting each sentence on it's own line?

2024-03-18 15:49 UTC, fabcor-maxiv commented on docs/source/dev/hwobj_signals.md
> semantic break is the same things as putting each sentence on it's own line?

No.

I never read the full document, only the introduction, I do not see much point in being strict about this. But to me, the important thing is to break long paragraphs where it makes sense logically.

So in Markdown I would write like this:

```none
I never read the full document, only the introduction,
I do not see much point in being strict about this.
But to me, the important thing is to break long paragraphs
where it makes sense logically.
```

2024-03-20 08:57 UTC, meguiraun commented
preview in https://mxcubecore--866.org.readthedocs.build/en/866/dev/hwobj_signals.html

2024-03-20 09:47 UTC, beteva commented
Very good job @meguiraun 👍
The device and the equipment signals are definitely deprecated. Quite some time ago there was a decision not to use Device and Equipment class any more.
You are right, we should remove the update signal and only use valueChanged.
You can also remove the xrf related signals - in my WIP for xrf I've changed them all to stateChanged

2024-03-20 09:55 UTC, marcus-oscarsson commented
Well done ! very nice !. As Antonia already pointed out, we should really start to remove the Device and Equipment classes.

2024-03-20 11:54 UTC, rhfogh commented on docs/source/dev/hwobj_signals.md
> +The {py:class}`mxcubecore.BaseHardwareObjects.HardwareObject` class serves as the base class for all hardware objects in MXCuBE. It includes methods for defining and emitting signals, allowing derive
Strictly speaking it is the HardwareObjectMixin class (which also includes YML-configured objects). Once we unify the YAML and XML cconfiguration this distinction should hopefully disappear.

2024-03-20 12:38 UTC, meguiraun commented on docs/source/dev/hwobj_signals.md
> +The {py:class}`mxcubecore.BaseHardwareObjects.HardwareObject` class serves as the base class for all hardware objects in MXCuBE. It includes methods for defining and emitting signals, allowing derive
added this clarification in the text

2024-03-20 12:38 UTC, meguiraun commented
while the signals are still there, I simply marked as deprecated. 
Also added queue and diffractometer

2024-03-20 15:17 UTC, axelboc commented on docs/source/dev/hwobj_signals.md
> +Depending on the installed modules, signals are emitted using [Louie](https://pypi.org/project/Louie/) or [PyDispatcher](https://pypi.org/project/PyDispatcher/). The former being based on the later.
```suggestion
Depending on the installed modules, signals are emitted using [Louie](https://pypi.org/project/Louie/) or [PyDispatcher](https://pypi.org/project/PyDispatcher/). The former being based on the latter. The developer does not need to deal with the differences between those two modules as it is already being handled in the file [`dispatcher.py`](https://github.com/mxcube/mxcubecore/blob/develop/mxcubecore/dispatcher.py).
```

2024-03-20 15:17 UTC, axelboc commented on docs/source/dev/hwobj_signals.md
> +>Strictly speaking it is the HardwareObject OR HardwareObjectYaml class (both inherit from HardwareObjectMixin). Once we unify the YAML and XML configuration this distinction should hopefully disappe
```suggestion
> Strictly speaking it is the `HardwareObject` OR `HardwareObjectYaml` class (both inherit from `HardwareObjectMixin`). Once we unify the YAML and XML configuration, this distinction should hopefully disappear.
```

2024-03-20 15:17 UTC, axelboc commented on docs/source/dev/hwobj_signals.md
> +```
Not convinced this code sample is needed. Same with `connect` below. One can always go look in the classes mentioned. There is also the risk that the docs might fall out of sync in the future if the code ever changes.

2024-03-20 15:17 UTC, axelboc commented on docs/source/dev/hwobj_signals.md
> +> At least one entry must appear in the beamline's YAML configuration file. In this case I left the procedure mockup only, all the other mockups are commented. That is why only a few items appear in
Maybe reword to avoid using the first person "I"?

2024-03-20 15:17 UTC, axelboc commented on docs/source/dev/hwobj_signals.md
> +The following tables list the generic signals as well the signals from the some of the most important hardware objects.
```suggestion
The following tables list the generic signals as well as the signals from some of the most important hardware objects. 
```

2024-03-20 15:17 UTC, axelboc commented on mxcubecore/HardwareObjects/abstract/AbstractActuator.py
> +    valueChanged: during hwobj initialization and when setting a new value. Format: (   valueChanged, new_value)
```suggestion
    valueChanged: during hwobj initialization and when setting a new value. Format: (valueChanged, new_value)
```

2024-03-20 15:17 UTC, axelboc commented on mxcubecore/HardwareObjects/abstract/AbstractActuator.py
> +            read only flag, specified by XML property, otherwise `False`
```suggestion
            read-only flag, specified by XML property, otherwise `False`
```

2024-03-20 15:17 UTC, axelboc commented on mxcubecore/HardwareObjects/abstract/AbstractActuator.py
> +        Forces to emit all signals.
"Force" seems implied.

```suggestion
        Emit all signals.
```

Alternatively, in the next file, you've used the word "Reemit".

2024-03-20 15:17 UTC, axelboc commented on mxcubecore/HardwareObjects/abstract/AbstractAperture.py
> +        """Get diameters size list
Might as well be a bit more verbose:

```suggestion
        """Get list of diameter sizes.
```

2024-03-20 15:17 UTC, axelboc commented on mxcubecore/HardwareObjects/abstract/AbstractAperture.py
> +        """Get positions list
```suggestion
        """Get list of positions.
```

and so on ...

It's not always needed; for instance, the next one reads fine: "Get current diameter index"

2024-03-20 15:17 UTC, axelboc commented on mxcubecore/HardwareObjects/abstract/AbstractAperture.py
> +        """Reemits all signals
I would stick with the indicative mood everywhere:

```suggestion
        """Reemit all signals.
```

2024-03-20 15:17 UTC, axelboc commented on mxcubecore/HardwareObjects/abstract/AbstractCharacterisation.py
> +        Example: to set a site specific output directory.
```suggestion
        Example: to set a site-specific output directory.
```

2024-03-20 15:17 UTC, axelboc commented on mxcubecore/HardwareObjects/abstract/AbstractCollect.py
> +        Actual collect sequence.
```suggestion
        Actually collect the sequence.
```

2024-03-20 15:17 UTC, axelboc commented on mxcubecore/HardwareObjects/abstract/AbstractCollect.py
> +        """Collection finished beahviour
```suggestion
        """Collection finished behaviour
```

2024-03-20 15:17 UTC, axelboc commented on mxcubecore/HardwareObjects/abstract/AbstractCollect.py
> +        Take crytal snapshots of the currently loaded sample
```suggestion
        Take crystal snapshots of the currently loaded sample
```

2024-03-20 15:27 UTC, meguiraun commented on docs/source/dev/hwobj_signals.md
> +```
yeah I know, but I still think it makes the description easier to understand. That code has not changed much anyway in the recent mxcube history

2024-03-21 10:13 UTC, fabcor-maxiv approved these changes

2024-03-21 13:44 UTC, beteva reviewed
Very nice.
Apparently we need changes in many python files for better documentation. I suggest we see together with the other developers who does what, but I like the class description you've made for AbstractActuator. We should follow the same way.

2024-03-22 10:11 UTC, meguiraun commented
AbstractBeam with docstrings in class [here](https://mxcubecore--866.org.readthedocs.build/en/866/dev/autosummary/mxcubecore.HardwareObjects.abstract.AbstractBeam.html)
AbstracActuator with docstrings outside class [here](https://mxcubecore--866.org.readthedocs.build/en/866/dev/autosummary/mxcubecore.HardwareObjects.abstract.AbstractActuator.html)

I can remove all changes to the abstract classes if it makes the other PR easier to handle

ping @beteva

2024-03-22 10:53 UTC, fabcor-maxiv commented
> AbstractBeam with docstrings in class [here](https://mxcubecore--866.org.readthedocs.build/en/866/dev/autosummary/mxcubecore.HardwareObjects.abstract.AbstractBeam.html)
> AbstracActuator with docstrings outside class [here](https://mxcubecore--866.org.readthedocs.build/en/866/dev/autosummary/mxcubecore.HardwareObjects.abstract.AbstractActuator.html)

For me, this belongs in the class docstring : )

2024-03-22 11:58 UTC, meguiraun commented
> > AbstractBeam with docstrings in class [here](https://mxcubecore--866.org.readthedocs.build/en/866/dev/autosummary/mxcubecore.HardwareObjects.abstract.AbstractBeam.html)
> > AbstracActuator with docstrings outside class [here](https://mxcubecore--866.org.readthedocs.build/en/866/dev/autosummary/mxcubecore.HardwareObjects.abstract.AbstractActuator.html)
> 
> For me, this belongs in the class docstring : )

I think same way, it seems its place

2024-03-22 12:26 UTC, beteva commented
@meguiraun, agree the best place is the class docstrings.

2024-06-18 11:52 UTC, marcus-oscarsson commented
Hey @meguiraun, do you have an update on this one, it seemed almost done ?

2024-08-13 08:01 UTC, meguiraun commented
completely lost track of this one... so sorry...

If people are happy I am also happy. Not all the hwobjs are covered tough

2024-08-13 09:41 UTC, fabcor-maxiv commented
Not all checks are successful. After this is fixed, I think it is fine to merge. And then I might do follow-ups as I had already started in <https://github.com/mxcube/mxcubecore/pull/947>.

2024-08-16 09:46 UTC, meguiraun commented
all checks are green now!

2024-11-12 15:57 UTC, marcus-oscarsson commented
Sorry my mistake. I must have missed the last comments, was this ready to be merged ?

2025-01-27 14:35 UTC, marcus-oscarsson commented
@fabcor-maxiv, @elmjag. Sorry to take such a long time with this one. Is this one ready to be merged now. I think there's been a conflict for some time now ?

2025-01-27 14:53 UTC, fabcor-maxiv commented
It is still on my mind. I plan to take over this one and also integrate some of the work I started in <https://github.com/mxcube/mxcubecore/pull/947>. I assigned it to me.

2025-01-31 13:38 UTC, closed without merging

2025-01-31 13:45 UTC, fabcor-maxiv commented
Done in <https://github.com/mxcube/mxcubecore/pull/1116>.