[WIP] P11 develop 2
mxcube/mxcubecore pull request #873
Opened 2024-03-16 13:18 UTC by agruzinov

Small changes to the P11 HO after testing.

2024-03-18 08:11 UTC, fabcor-maxiv requested changes

2024-03-18 08:11 UTC, fabcor-maxiv commented on pyproject.toml
> +version = "1.77.0"
As far as I understood the process, that should not be done from within a pull request.

```suggestion
version = "1.76.0"
```

2024-03-18 08:14 UTC, marcus-oscarsson commented on pyproject.toml
> +version = "1.77.0"
Its indeed strange that the PR includes a previous commit, from the CI (#4f6c5d9)

2024-03-21 10:15 UTC, agruzinov commented
Is there a cleaner way to incorporate all the changes and having a fork without having all the commits that happened in between after rebase? 

For tnow it is like this:

There is a branch of core/qt under mu user.
Than:

-Synchronise all the changes that happened in between with the develop branch through the web interface. 
Than on the develop maschine:
git checkout develop
git pull (with rebase)

than:

git checkout p11_develop_2
git rebase develop
git push

Rhetorical question: what I'm doing wrong? :)

Or it is easier just to to work on the main repo than?

Any comments will be appreciated? Sorry for the basic question, but I think I've lost the understanding of the git behaviour.

Cheers!



git branch p11_develop_2

2024-03-21 10:25 UTC, agruzinov commented on pyproject.toml
> +version = "1.77.0"
That happens if I get the latest updated from the upstream develop to agruzinov/develop through github web interface.

2024-03-21 15:35 UTC, closed without merging

2024-03-21 15:35 UTC, agruzinov commented
Resolved through another PR#905. Closing.