[Documentation Code Camp] - Added introductory section for queue documentation
mxcube/mxcubecore pull request #889
Opened 2024-03-18 13:01 UTC by marcus-oscarsson

2024-03-18 13:39 UTC, rhfogh approved these changes

2024-03-18 14:17 UTC, marcus-oscarsson commented
This is still very much in progress, Ill try to add a bit more introduction and some figures that might make things easier to understand.  Then Ill go on with some more details that will point out where things are implemented and how new tasks are created.

2024-03-18 14:18 UTC, marcus-oscarsson commented
If you think about something that you'd like to know Id try to add it, I'm not promising that it will be any clearer but it least it will be documented ;)

2024-03-18 15:12 UTC, rhfogh commented
I do have one. As I understood the old system, there was a single source of truth, specifically the tree of QueueModelObjects. But (again as I understood it) MxcubeWeb introduced a new data structure that served as a competing source of truth that could be queried or modified independently. I'd like to understand what both those structures are and how they interact.

2024-03-18 15:16 UTC, marcus-oscarsson commented
Ill try to clarify that, the queue is the same in both Qt and Web, still the same old tree of `QueueModelObjects` but ill try to clarify that. The creation of the nodes differ slightly a bit but it should otherwise be the same.

2024-03-19 08:47 UTC, fabcor-maxiv reviewed
Same suggestion I made for the other pull requests: when dealing with markup I tend to prefer [Semantic Line Breaks](https://sembr.org/). It is a personal preference, as far as I know we do not have a policy for this, so feel free to follow it, to whatever degree you feel comfortable with, or not at all.

2024-03-19 08:51 UTC, fabcor-maxiv reviewed
Looks good overall

2024-03-19 08:51 UTC, fabcor-maxiv commented on docs/source/dev/queue.md
> +Today's MXCuBE queue system was first implemented in version 2.x of MXCuBE. The aim was to create a queuing system that provided means for automation and that integrated well with the sample changer
We are missing a title

```suggestion
# Queue system

## Introduction

Today's MXCuBE queue system was first implemented in version 2.x of MXCuBE. The aim was to create a queuing system that provided means for automation and that integrated well with the sample changer robots, the ISPyB LIMS system, and workflow engines. The queue was designed to have manual and automatic modes of operation.
```

2024-03-21 13:49 UTC, axelboc commented on docs/source/dev/queue.md
> +The combination of a `QueueEntry` and its model (`QueueModel`) is often referred to as an ask *task*, and makes up the entity that will be executed when the queue is executed.
```suggestion
The combination of a `QueueEntry` and its model (`QueueModel`) is often referred to as a *task*, and makes up the entity that will be executed when the queue is executed.
```

2024-03-21 13:49 UTC, axelboc commented on docs/source/dev/queue.md
> +# not displayed at all in the Web version
```suggestion
# In the Qt version, this item is displayed in the queue.
# In the Web version, it's not displayed at all.
```

2024-03-21 13:49 UTC, axelboc commented on docs/source/dev/queue.md
> +To enable automatic data collection over several samples, one needs to associate tasks to be performed on a set of samples. The decision was to represent the queue as a tree of nodes, where each node
I feel it's a bit confusing to describe the entire queue as a tree of nodes that contains sample nodes and task nodes. From what I understand, there's basically a flat queue of sample "entries" at the top, and each sample entry is associated with a tree of task "nodes".

2024-03-21 13:49 UTC, axelboc commented on docs/source/dev/queue.md
> +*enqueued*
Yeah ... I'm lost :sweat_smile: — a small diagram would probably be worth a thousand words. :joy:

2024-03-21 13:55 UTC, marcus-oscarsson commented on docs/source/dev/queue.md
> +To enable automatic data collection over several samples, one needs to associate tasks to be performed on a set of samples. The decision was to represent the queue as a tree of nodes, where each node
No, its a tree !

2024-03-21 13:56 UTC, marcus-oscarsson commented
I'm sorry @axelboc  but I'm not done yet its still very much work in progress this but ill make a diagram as well

2024-03-21 14:06 UTC, marcus-oscarsson commented on docs/source/dev/queue.md
> +To enable automatic data collection over several samples, one needs to associate tasks to be performed on a set of samples. The decision was to represent the queue as a tree of nodes, where each node
Its made to look flatter than it really is on the web UI side

2024-03-21 14:48 UTC, fabcor-maxiv commented on docs/source/dev/queue.md
> +*enqueued*
I also like diagrams! : D

In case it helps... We can enable [graphviz](https://www.sphinx-doc.org/en/master/usage/extensions/graphviz.html) if not enabled yet.

There are probably other extensions out there:
* <https://github.com/sphinx-contrib/>
* <https://github.com/yoloseem/awesome-sphinxdoc>
* <https://sphinx-extensions.readthedocs.io>

2024-03-21 14:54 UTC, marcus-oscarsson commented on docs/source/dev/queue.md
> +*enqueued*
Hm, I think Id prefer to create the diagram myself in this case but perhaps for other things

2024-03-21 15:03 UTC, axelboc commented on docs/source/dev/queue.md
> +To enable automatic data collection over several samples, one needs to associate tasks to be performed on a set of samples. The decision was to represent the queue as a tree of nodes, where each node
:exploding_head: but then is it a tree of "sample entries" and each entry has its own tree of "task nodes", or are sample nodes and task nodes truly mingled with one another inside the same tree?

2024-03-21 15:04 UTC, axelboc commented on docs/source/dev/queue.md
> +*enqueued*
I know of [mermaid](https://mermaid.js.org/intro/)

2024-03-21 15:09 UTC, marcus-oscarsson commented on docs/source/dev/queue.md
> +To enable automatic data collection over several samples, one needs to associate tasks to be performed on a set of samples. The decision was to represent the queue as a tree of nodes, where each node
Ill make a figure and maybe it makes things easier to understand, I never tried to put a Sample node on a Group node, but that could actually work (not that it makes alot of sense)

Basically:

Root
  Sample 1
    Group 1
      Task 1
      Task 2
     ....
   Group N
     Task 1
     Task 2
   Sample 2
    .  ...

2024-03-21 15:12 UTC, marcus-oscarsson commented on docs/source/dev/queue.md
> +To enable automatic data collection over several samples, one needs to associate tasks to be performed on a set of samples. The decision was to represent the queue as a tree of nodes, where each node
In the Qt version the queue is both displayed and executed like this

2024-03-21 15:13 UTC, marcus-oscarsson commented on docs/source/dev/queue.md
> +To enable automatic data collection over several samples, one needs to associate tasks to be performed on a set of samples. The decision was to represent the queue as a tree of nodes, where each node
In the web version the Group nodes are not displayed and the queue is displayed one sample at the time, but that is an illusion. When we run the queue in automatic mode, the above is what gets executed

2024-03-21 15:15 UTC, marcus-oscarsson commented on docs/source/dev/queue.md
> +To enable automatic data collection over several samples, one needs to associate tasks to be performed on a set of samples. The decision was to represent the queue as a tree of nodes, where each node
When we run it sample by sample we explicitly disable all entries except for the entry we want to execute the queue. This is very explicit in the Qt version because each item can be enabled and disabled by a checkbox in the web version this was made implicit. The later was a wish from the scientists  because the prior was considered to be to complicated and confusing when there were lots of samples.

2024-03-21 15:16 UTC, marcus-oscarsson commented on docs/source/dev/queue.md
> +To enable automatic data collection over several samples, one needs to associate tasks to be performed on a set of samples. The decision was to represent the queue as a tree of nodes, where each node
Maybe it helps, but Ill try to clarify and make a diagram

2024-03-21 15:20 UTC, fabcor-maxiv commented on docs/source/dev/queue.md
> +*enqueued*
Yes, that is mermaid and plantuml that I had in mind (rather than graphviz, even though it works fine for simple things). The good thing is that we directly have the diagram as code inside the document (inside the Markdown or ReStructuredText). I opened a ticket <https://github.com/mxcube/mxcubecore/issues/908> to gather the info, in case someone ever wants/needs to do a diagram this way.

2024-03-21 15:24 UTC, marcus-oscarsson commented on docs/source/dev/queue.md
> +*enqueued*
Aha, okey you mean like that. I thought that you mean that the diagram would generated from the source. In that case its much more useful :)

2024-03-21 15:28 UTC, axelboc commented on docs/source/dev/queue.md
> +To enable automatic data collection over several samples, one needs to associate tasks to be performed on a set of samples. The decision was to represent the queue as a tree of nodes, where each node
Nice, thanks, it does clear things up a lot!

> I never tried to put a Sample node on a Group node, but that could actually work (not that it makes alot of sense)

I guess this is my point: the fact that it's a very flexible tree structure under the hood does not necessarily need to be documented. If the recommended/actual usage of the queue is that samples are always directly under the root of the tree, then the explanations and terminology can be dumbed down a lot (and arguably the code as well, but that's another debate).

2024-03-21 15:42 UTC, marcus-oscarsson commented on docs/source/dev/queue.md
> +To enable automatic data collection over several samples, one needs to associate tasks to be performed on a set of samples. The decision was to represent the queue as a tree of nodes, where each node
It was designed flexible on purpose  to make it easy to extend/adapt. There were lots of ideas regarding automation at the time (and there still is) so we needed to be quite flexible and did not want to risk coming up with a system that did not fit what the scientists possibly wanted to do in the future.

The implementation as it is today can be simplified without loosing functionality, and that is partially also what we want to do with the refactoring of the queue that we speak about sometimes. The queue could be implemented in many different ways, it can be a completely flat structure but then there has to be something else that defines the relation between the "entries". 

I understand what you mean, somehow I prefer to document as it really is as its for developers and then perhaps add a additional explanations on what simplifications that are or can be done.

2024-03-21 22:00 UTC, AnnieHeroux commented on docs/source/dev/queue.md
> +On a technical level, there is a tight coupling between the `QueueEntry` base class to a Qt view object that makes the creation of the object slightly different between the two user interfaces (Qt an
To handle the tight coupling to Qt a `Mock` object used in the Web version instead of a Qt view and the handling of the updating of the view in the web version handled through signals passed over websockets to the client.

This sentence might be better if split in two????? So the Web has a Mock object to mimic the Qt?

2024-03-22 07:55 UTC, marcus-oscarsson commented on docs/source/dev/queue.md
> +On a technical level, there is a tight coupling between the `QueueEntry` base class to a Qt view object that makes the creation of the object slightly different between the two user interfaces (Qt an
Yes, you are right. That sentence is a a bit convoluted

2024-03-22 07:55 UTC, marcus-oscarsson commented on docs/source/dev/queue.md
> +On a technical level, there is a tight coupling between the `QueueEntry` base class to a Qt view object that makes the creation of the object slightly different between the two user interfaces (Qt an
"This sentence might be better if split in two????? So the Web has a Mock object to mimic the Qt?"

Yes

2024-03-22 10:19 UTC, rhfogh commented
AH, one question here:

In the diagram it is shown with Samples always at the top ()makes sense) and with only one level of DataCollectionGroup. Is that a rule, just common practice, or a coincidence? When running multisweep workflow experiments, it arguably makes more sense to have multiple levels or groupings, a group for the entire workflow, containing another group for teh characterisation, and yet another group for the actual acquisition sweeps. And indeed this is how I have coded the GPhL workflow. I think we need to decide whether we accept multiple levels of groupings or not, and make it explicit in the documentation, otherwise people will start making incorrect assumptions and different bits of code can clash.

2024-03-22 10:20 UTC, rhfogh requested changes
We need to sort out the question of whether nested groups are allowed or not.

Great with the diagrams, BTW, that makes everything a lot clearer.

2024-03-22 11:19 UTC, axelboc commented on docs/source/dev/queue.md
> +*enqueued*
Thanks for the diagram!

2024-03-22 11:49 UTC, fabcor-maxiv requested changes

2024-03-22 11:49 UTC, fabcor-maxiv commented on docs/source/dev/queue.md
> +```{figure} /assets/queue_execute_methods.svg
This file is missing

2024-03-22 12:39 UTC, marcus-oscarsson commented on docs/source/dev/queue.md
> +```{figure} /assets/queue_execute_methods.svg
Thanks, I'm aware, I'm still working on it. Also trying to get the scaling to work

2024-03-22 12:44 UTC, marcus-oscarsson commented
@rhfogh, I'm still working on this section and ill try to make some notes on whats common practice between what is possible. There is not decision on how deep one can nest data collection groups or samples for that matter. Its left open by purpose. The conventional one crystal type per pin with sample changer collection is whats shown in the figure, Ill make a note on that.

One can imagine that for instance a plate sample changer where once have two levels of samples plate and crystal, I'm not saying that thats how it should be done but its a possibility. For workflows nested groups could make sense and even for multi sweep collections.

2024-03-22 12:51 UTC, rhfogh commented
OK, If you will put in something explicit about allowing nested groups, I'll remove my 'Request Changes' immediately and leave the rest to you. I made the point because (until I modified it) there was code assuming that the Sample was  always two levels up from the DataCollection.

I still need to check with Olof exactly what the rules and assumptions about grouping are for MASSIF-1 operation.

2024-03-22 12:52 UTC, rhfogh approved these changes
Approved, given that there will be some wording on the fact that e.g. nested DataCollectionGroups are allowed.

2024-03-22 12:53 UTC, marcus-oscarsson commented
I'm not sure how to approach this because I make some changes and push mostly to see how it renders, but then I get comments on certain things that are still in progress. As its draft Ill try to answer your general questions regarding the queue like the one @rhfogh asked, and the rest is still very much subject to change.

2024-03-22 12:55 UTC, rhfogh commented
You could mark it as WIP, if you prefer that we wait with the comments.

2024-03-22 12:59 UTC, axelboc commented
We just got mixed on what "Draft" means. Marcus opened this to show progress, not to request a review. As discussed during the meeting this morning, "Draft" means that it's not yet ready for review (unless the opener specifically asks for feedback). The removal of "Draft" status by the opener means that reviews are welcome.

2024-03-22 13:05 UTC, marcus-oscarsson commented
I happy for the broader questions like the one @rhfogh asked or general questions about the queue that you'd like to know about, it helps me to narrow down on some details. Just to avoid that we waste our time on things that will most likely change. I also mark it as WIP ;)

2024-04-16 10:24 UTC, marcus-oscarsson commented
I believe this is starting to get usable, its not complete yet I will add a few sections in a near future. I plan on adding more on how the execution works and then Ill add something about the new queue design and the drawbacks of the current design. However, thats for Part 2 :)

2024-04-16 11:03 UTC, beteva commented
Nice with diagrams.

2024-04-16 12:20 UTC, rhfogh commented on docs/source/dev/queue.md
> +and the nesting occurs at the group level. The depth of nesting is currently maximum 3 - Sample -
That is not actually the case for GPhL workflow - we nest more deeply. Maybe we should change that. This probably needs discussion, to make sure that everybody either is or is not ready for deeper nesting.

2024-04-16 12:36 UTC, rhfogh commented on docs/source/dev/queue.md
> +Each type of data collection protocol has a piece of code similar to the code above associated with it. In the Web version, this is done in mxcubeweb.components.queue.py in the methods called add_**t
I think we should say explicitly that in the Qt version enqueueing the queue entry is done automatically when the qmo is added to the queue, via the QueueModel.add_child function, which sends out a child_added signal. It seems - to a *very* quick look - that the same is the case in the web version, via the function components.queue.Queue.queue_model_child_added. Maybe this should have a more prominent place in thedocumentation. Actually, is it the rule or an exception when enqueue is called explicitly rather than via signal?

2024-04-16 12:37 UTC, rhfogh requested changes
Very nice, but I think a couple of things for a quick discussion

2024-04-16 12:50 UTC, marcus-oscarsson commented on docs/source/dev/queue.md
> +and the nesting occurs at the group level. The depth of nesting is currently maximum 3 - Sample -
That's not an issue, If you know how many levels you nest Ill update with that figure or phrase it like "the most common nesting depth is 3" or similair

2024-04-16 12:55 UTC, marcus-oscarsson commented on docs/source/dev/queue.md
> +Each type of data collection protocol has a piece of code similar to the code above associated with it. In the Web version, this is done in mxcubeweb.components.queue.py in the methods called add_**t
Its not entirely correct for the web version because its only the case for collections added through workflows that use the signal, the rest is done through `enqueue`. Ill see what I can do

2024-04-16 13:32 UTC, marcus-oscarsson commented on docs/source/dev/queue.md
> +Each type of data collection protocol has a piece of code similar to the code above associated with it. In the Web version, this is done in mxcubeweb.components.queue.py in the methods called add_**t
Thanks, I tried to make some clarify a bit, let me know what you think ?

2024-04-16 13:33 UTC, marcus-oscarsson commented on docs/source/dev/queue.md
> +and the nesting occurs at the group level. The depth of nesting is currently maximum 3 - Sample -
So, I added a "disclaimer" for workflows, but let me know if you rather that we add a figure.

2024-04-26 11:45 UTC, merged