misc typo fixes and small clean-ups
mxcube/mxcubecore pull request #959
Opened 2024-07-05 14:51 UTC by elmjag

Some small clean-up and fixes:

* GenericDiffractometer: fix debug log message
* remove unused code
* fix typos in error messages, comments and doc strings

2024-07-05 15:09 UTC, rhfogh commented on mxcubecore/HardwareObjects/abstract/AbstractDetector.py
> -from mxcubecore import HardwareRepository as HWR
You also need to remove a few obsolete lines around line 227-231 where HWR is used

2024-07-05 15:10 UTC, rhfogh requested changes
Very good work, thanks. Just the one extra change (unless you have dealt with it already)

2024-07-06 15:30 UTC, elmjag commented on mxcubecore/HardwareObjects/abstract/AbstractDetector.py
> -from mxcubecore import HardwareRepository as HWR
Ugh, that was a mistake to remove that import. I have put it back!

2024-07-07 11:12 UTC, rhfogh approved these changes

2024-07-07 11:13 UTC, merged