P11 char
mxcube/mxcubecore pull request #966
Opened 2024-07-08 14:53 UTC by agruzinov

Code changes in the P11 files to make the characterization properly executed using EDNA.

2024-07-08 15:33 UTC, agruzinov commented
I did black several times, and it looks happy on several machines...

2024-08-13 12:55 UTC, agruzinov commented
It is ready for a review now.

2024-08-13 13:45 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/DigitalZoomMotor.py
> +            self.is_ready()
This is always True. Is this what you want?

2024-08-13 13:45 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/DigitalZoomMotor.py
> +class DigitalZoomMotor(AbstractMotor, HardwareObject):
AbstractMotor inherits from HardwareObject. Did not look at the rest of the code, but is it necessary to inherit from HardwareObject?

2024-08-13 13:45 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/MjpgStreamVideo.py
> +        self.is_ready()
is_ready only returns True/False, does not set the state. This line looks strange.

2024-08-13 13:45 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/MjpgStreamVideo.py
> +class MjpgStreamVideo(AbstractVideoDevice, HardwareObject):
AbstractVideoDevice inherits from HardwareObject. Is it necessary to inherit from HardwareObject?

2024-08-13 13:45 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/P11MachineInfo.py
> +
Maybe it is worth checking the TangoMachineInfo, which does the same job (except for the simulated values).

2024-08-13 13:45 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/P11Session.py
>          super().__init__(*args)
You can remove this.

2024-08-13 13:45 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/P11Zoom.py
>          AbstractNState.__init__(self, name)
I would use` super().__init__(name)` instead.

2024-08-13 14:02 UTC, fabcor-maxiv reviewed
Many of the files in this pull request contain no meaningful change, but only formatting (empty lines, and imports). I guess it is fine because they needed to be reformatted one day or another, but that is unexpected and a bit confusing.

The contribution guideline says to use Google style for docstrings: https://mxcubecore.readthedocs.io/en/stable/dev/contributing.html#style-guidlines

2024-08-13 14:02 UTC, fabcor-maxiv commented on mxcubecore/HardwareObjects/DESY/MjpgStreamVideo.py
> +        self.is_ready()
That seems strange... Does this method do something or is it a getter?

2024-08-13 14:02 UTC, fabcor-maxiv commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +        #     )
```suggestion
```

2024-08-13 14:02 UTC, fabcor-maxiv commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +                # filepath = os.path.join(basepath, "%s_%d" % (prefix, runno))
```suggestion
```

2024-08-13 14:02 UTC, fabcor-maxiv commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +                # )
```suggestion
```

2024-08-13 14:02 UTC, fabcor-maxiv commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +        """
The contribution guideline says to use Google style for docstrings: https://mxcubecore.readthedocs.io/en/stable/dev/contributing.html#style-guidlines

2024-08-13 14:02 UTC, fabcor-maxiv commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +        """
Use google style for docstrings

2024-08-13 14:02 UTC, fabcor-maxiv commented on mxcubecore/HardwareObjects/DESY/P11MachineInfo.py
> +"""
Is this docstring correct? It does not seem so, because of the name for example. Anyway it looks like a class docstring so it should be part of the class, and there are some formatting issues in this docstring.

2024-08-13 14:02 UTC, fabcor-maxiv commented on mxcubecore/HardwareObjects/DESY/P11MachineInfo.py
> +pass
This line probably does not belong here.

```suggestion
```

2024-08-13 14:02 UTC, fabcor-maxiv commented on mxcubecore/HardwareObjects/DESY/P11NanoDiff.py
> +        #     self.init_ok = True
```suggestion
```

2024-09-02 13:00 UTC, agruzinov commented
Thanks a lot for everyone for the comments. I've tried to incorporate most of them except the doc strings.

If the rest is fine I would suggests to merge it like now and that I'll submit another PR for the docstrings.

2024-09-02 13:09 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11NanoDiff.py
> +        #     self.init_ok = True
There are still some issues with data collection. That is why I still need some of the commented code. Once it will reach the equilibrium, my plan is to do the polishing. Thanks for noting that.

2024-09-02 13:10 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Zoom.py
>          AbstractNState.__init__(self, name)
Thanks for the comments. I've removed the respecting code parts.

2024-09-02 14:00 UTC, rhfogh commented on mxcubecore/HardwareObjects/abstract/AbstractCollect.py
> +        """def get_beam_
This does not look right. Why 'get_beam' if the function is 'set_transmission'? Better nothing than something wrong.

2024-09-02 14:24 UTC, fabcor-maxiv requested changes, later dismissed
I reviewed only the common parts, I ignored what has changed in `DESY` directory.

2024-09-02 14:24 UTC, fabcor-maxiv commented on mxcubecore/HardwareObjects/MotorsNPosition.py
> +            return
Why are we not returning anything here? When the last line of this function is `return current_idx`? This does not seem okay.

2024-09-02 14:37 UTC, beteva requested changes

2024-09-02 14:37 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        self.pinhole_hwobj = self.get_object_by_role("pinhole")
Maybe it is more consistent if you move this to init,.

2024-09-02 14:37 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +
Is there a reason that you duplicate part of the `AbstractBeam.__init__` and you change the aperture and slits size values?
Is there a reason you change the beam sshape from UNKNOWN to ELLIPTICAL in `__init__`.

2024-09-02 14:37 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        return self._beam_info_dict
Is there a reason why you duplicate the  AbstractBeam evaluate_beam_info?

2024-09-02 14:37 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +            self.log.debug(f"Energy value set to {value}.")
May I suggest that you put your logic rather in your P11Energy implementation, not in the Collect. You may need the same for moving the energy as a motor or when you change the wavelength. Thus whenever you do set_value, you will have the test for whether to move or not and  `HWR.beamline.energy.set_value(value)` here would be enough.

2024-09-02 14:37 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/P11MachineInfo.py
> +    default_maschine_energy = 6.08  # GeV
Is this a mockup?

2024-09-02 14:37 UTC, agruzinov commented on mxcubecore/HardwareObjects/abstract/AbstractCollect.py
> +        """def get_beam_
No idea how it is landed there, Thanks for checking. Removed.

2024-09-02 14:41 UTC, agruzinov commented on mxcubecore/HardwareObjects/MotorsNPosition.py
> +            return
This is due to the previous error when the at some point updating recursion was happening with the error. So this is to prevent it updating if it is updating already.

2024-09-02 14:47 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11MachineInfo.py
> +    default_maschine_energy = 6.08  # GeV
In a sense, it is not completely finished for P11.

2024-09-02 14:59 UTC, fabcor-maxiv commented on mxcubecore/HardwareObjects/MotorsNPosition.py
> +            return
But should this function return something or not? The last line of the function return a value. That is why I am confused...

2024-09-02 15:04 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        self.pinhole_hwobj = self.get_object_by_role("pinhole")
Done

2024-09-02 15:05 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +
No particular reason. Cleaned -up.

2024-09-02 15:11 UTC, beteva commented on mxcubecore/HardwareObjects/MotorsNPosition.py
> +            return
I am wondering is it not simpler to configure those motors as NState devices, so this class may not be even needed.
Or I am too naive?

2024-09-02 15:15 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        return self._beam_info_dict
I was too fast. The previous realization had this. After update it is not needed. Removed. Thanks for noticing.

2024-09-02 15:17 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +
This class is defined in AbstractBeam, simple import should do it.

2024-09-02 16:14 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +            self.log.debug(f"Energy value set to {value}.")
Thanks for comment. Moved to P11Energy.

2024-09-02 16:21 UTC, agruzinov commented on mxcubecore/HardwareObjects/MotorsNPosition.py
> +            return
IN this case it should not return anything. I've substituted it with pass. 
I need to look into reimplementation. I can not tell right know. I would avoid touching it just yet.

2024-09-03 06:13 UTC, fabcor-maxiv commented on mxcubecore/HardwareObjects/MotorsNPosition.py
> +            return
> IN this case it should not return anything.

But this method `update_multi_value` must always return a value, or not? For example here:

https://github.com/mxcube/mxcubecore/blob/8cd71300604b0646be497e90c8d8aab2799b0de0/mxcubecore/HardwareObjects/MotorsNPosition.py#L135

> IN this case it should not return anything. I've substituted it with pass.

I have no idea what this is supposed to achieve. :D

>  I need to look into reimplementation. I can not tell right know. I would avoid touching it just yet.

Yes, this needs to be rethought, I do not think it should be merged as it is now.

2024-09-03 13:10 UTC, fabcor-maxiv commented on mxcubecore/HardwareObjects/MotorsNPosition.py
> +        self._updating_multi_value = True
This does not make sense to me. As far as I can tell this `if` clause does not do anything. Maybe the `if` clause needs to be removed entirely.

```suggestion
        self._updating_multi_value = True
```

2024-09-05 09:44 UTC, rhfogh commented on mxcubecore/HardwareObjects/MotorsNPosition.py
> +        self._updating_multi_value = True
The change looks problematic too. The basic ideas seems to be to avoid having this function called indirectly while it is already being executed. To achieve this
1) decide what shoudl be returned from these recursive calls. Since the 'no current position' value seems to be -1, maybe that would be a better choice. 

2) I would propose to start with

  current_idx = -1
    if not self._updating_multi_value:
      self._updating_multi_value = True
      try:
        Put the entire body of the function here
        Then end with:

      finally:
    self._updating_multi_value = False
  return current_idx

2024-09-05 09:51 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/DigitalZoomMotor.py
> +class DigitalZoomMotor(AbstractMotor, HardwareObject):
Agree with Antonia

2024-09-05 09:54 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        self.pinhole_hwobj = self.get_object_by_role("pinhole")
Now nothing is happening in __init__ you chould remove the function altogether. There is no need for a function when the only thing it does is to call teh same superclass function

2024-09-05 09:57 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +            value = -1
This line is unnecessary and  can be removed

2024-09-05 10:14 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        return self._beam_info_dict
Looks like the function is still there, and the only difference seems to be the conversion to a numpy array before finding the min. What does that add compared to just doing min(self._beam_size_dict.values())

2024-09-05 10:18 UTC, rhfogh commented on mxcubecore/HardwareObjects/DESY/P11DetectorDistance.py
> +                state = self.STATES.READY
Should update_state also be  called when you reach state READY? With this code it does not.

2024-09-05 11:32 UTC, rhfogh requested changes
I only went through parts of this, but it looks OK. The outstanding comments should be addressed, though.

2024-09-06 08:12 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        self.pinhole_hwobj = self.get_object_by_role("pinhole")
Agree with @rhfogh

2024-09-06 08:12 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        return self._beam_info_dict
evaluate_beam_info is still there.

2024-09-06 08:12 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/P11MachineInfo.py
> +
@agruzinov , did you look at TangoMachineInfo?

2024-09-06 08:12 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/P11Transmission.py
>          limits = self.get_property("limits", None)
You can use the AbstractActuator limits handling and remove it from your HO if you just change in the xml file "limits" to "default_limits".

2024-09-06 08:12 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/P11Transmission.py
>          limits = self.get_property("limits", None)
You can also remove the value_changed method, as it is already handled in the AbstractActuator.

2024-09-06 08:19 UTC, beteva commented
@agruzinov sorry for being fussy. I see that there is a lot of legacy code in the P11 HardwareObjects and you are doing good cleaning and adaptation job.

2024-09-06 14:10 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        return self._beam_info_dict
OK, afetr looking closer, if I did not modify it, i'm getting a bunch of errors about the conversion

2024-09-06 14:10 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        return self._beam_info_dict
2024-09-06 16:09:20,054 |HWR  |ERROR  | Cannot load brick beam_size_brick : initialization failed
Traceback (most recent call last):
  File "/gpfs/local/shared/MXCuBE/mxcubeqt/mxcubeqt/configuration.py", line 82, in load_brick
    new_instance = class_obj(None, brick_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/local/shared/MXCuBE/mxcubeqt/mxcubeqt/bricks/beam_size_brick.py", line 123, in __init__
    self.connect(HWR.beamline.beam, "beamInfoChanged", self.beam_info_changed)
  File "/gpfs/local/shared/MXCuBE/mxcubeqt/mxcubeqt/base_components.py", line 772, in connect_hwobj
    _sender = emitter(sender)
              ^^^^^^^^^^^^^^^
  File "/gpfs/local/shared/MXCuBE/mxcubeqt/mxcubeqt/base_components.py", line 66, in emitter
    _emitter_cache[ob] = _QObject(ho=ob)
    ~~~~~~~~~~~~~~^^^^
  File "/home/p11user/.localpython3119/lib/python3.11/weakref.py", line 428, in __setitem__
    self.data[ref(key, self._remove)] = value
              ^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot create weak reference to 'NoneType' object
2024-09-06 16:09:20,095 |HWR.P11Pinhole|DEBUG  |      - motor pinholey is at -235
2024-09-06 16:09:20,095 |HWR.P11Pinhole|DEBUG  |      - motor pinholez is at -13986
2024-09-06 16:09:20,138 |HWR  |ERROR  | Cannot load brick task_toolbox_brick : initialization failed
Traceback (most recent call last):
  File "/gpfs/local/shared/MXCuBE/mxcubeqt/mxcubeqt/configuration.py", line 82, in load_brick
    new_instance = class_obj(None, brick_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/local/shared/MXCuBE/mxcubeqt/mxcubeqt/bricks/task_toolbox_brick.py", line 67, in __init__
    self.task_tool_box_widget = TaskToolBoxWidget(self)
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/local/shared/MXCuBE/mxcubeqt/mxcubeqt/widgets/task_toolbox_widget.py", line 69, in __init__
    self.discrete_page = CreateDiscreteWidget(self.tool_box, "Discrete")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/local/shared/MXCuBE/mxcubeqt/mxcubeqt/widgets/create_discrete_widget.py", line 44, in __init__
    CreateTaskBase.__init__(
  File "/gpfs/local/shared/MXCuBE/mxcubeqt/mxcubeqt/widgets/create_task_base.py", line 105, in __init__
    HWR.beamline.beam.connect(
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'connect'

2024-09-06 14:11 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        return self._beam_info_dict
2024-09-06 16:09:15,038 |HWR  |ERROR  | Cannot initialize Hardware Object "/beam"
Traceback (most recent call last):
  File "/gpfs/local/shared/MXCuBE/mxcubecore/mxcubecore/HardwareRepository.py", line 472, in _load_hardware_object
    hwobj_instance.init()
  File "/gpfs/local/shared/MXCuBE/mxcubecore/mxcubecore/HardwareObjects/DESY/P11Beam.py", line 56, in init
    self.mirror_idx_changed()
  File "/gpfs/local/shared/MXCuBE/mxcubecore/mxcubecore/HardwareObjects/DESY/P11Beam.py", line 131, in mirror_idx_changed
    self.evaluate_beam_info()
  File "/gpfs/local/shared/MXCuBE/mxcubecore/mxcubecore/HardwareObjects/abstract/AbstractBeam.py", line 221, in evaluate_beam_info
    _size = min(self._beam_size_dict.values())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'list' and 'tuple'
2024-09-06 16:09:15,135 |HWR  |ERROR  | Cannot initialize Hardware Object "/flux"
Traceback (most recent call last):
  File "/gpfs/local/shared/MXCuBE/mxcubecore/mxcubecore/HardwareRepository.py", line 472, in _load_hardware_object
    hwobj_instance.init()
  File "/gpfs/local/shared/MXCuBE/mxcubecore/mxcubecore/HardwareObjects/DESY/P11Flux.py", line 49, in init
    self.measure_flux()
  File "/gpfs/local/shared/MXCuBE/mxcubecore/mxcubecore/HardwareObjects/DESY/P11Flux.py", line 59, in measure_flux
    beam_size = HWR.beamline.beam.get_beam_size()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_beam_size'

2024-09-06 14:11 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        return self._beam_info_dict
2024-09-06 16:09:19,090 |HWR  |ERROR  | Cannot initialize Hardware Object "/mxcollect"
Traceback (most recent call last):
  File "/gpfs/local/shared/MXCuBE/mxcubecore/mxcubecore/HardwareRepository.py", line 472, in _load_hardware_object
    hwobj_instance.init()
  File "/gpfs/local/shared/MXCuBE/mxcubecore/mxcubecore/HardwareObjects/DESY/P11Collect.py", line 54, in init
    super().init()
  File "/gpfs/local/shared/MXCuBE/mxcubecore/mxcubecore/HardwareObjects/abstract/AbstractCollect.py", line 98, in init
    beam_div_hor, beam_div_ver = HWR.beamline.beam.get_beam_divergence()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_beam_divergence'

2024-09-06 14:12 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        return self._beam_info_dict
AttributeError: 'NoneType' object has no attribute 'get_beam_divergence'
+==================================================================================================================+
| role                 | Class                     | file                            | Time (ms)| Comment                   
+==================================================================================================================+
| beamline             | Beamline                  | beamline_config.yml             | 11       | Start loading contents:   
| session              | P11Session                | session.xml                     | 55       |                           
| machine_info         | P11MachineInfo            | mach-info.xml                   | 58       |                           
| transmission         | P11Transmission           | transmission.xml                | 38       |                           
| energy               | P11Energy                 | energy.xml                      | 22       |                           
| beam                 | None                      | beam.xml                        | 27       | No object loaded          
| flux                 | None                      | flux.xml                        | 97       | No object loaded          
| detector             | P11EigerDetector          | eiger.xml                       | 64       |                           
| resolution           | Resolution                | resolution.xml                  | 4        |                           
| hutch_interlock      | DoorInterlockMockup       | door-interlock-mockup.xml       | 0        |                           
| safety_shutter       | P11Shutter                | shutter-eh.xml                  | 9        |                           
| fast_shutter         | P11FastShutter            | fast-shutter.xml                | 7        |                           
| sample_changer       | P11SampleChanger          | sample-changer.xml              | 83       |                           
| diffractometer       | P11NanoDiff               | nanodiff.xml                    | 3306     |                           
| sample_view          | QtGraphicsManager         | sample-view.xml                 | 7        |                           
| lims                 | P11ISPyBClient            | lims.xml                        | 443      |                           
| queue_manager        | QueueManager              | queue.xml                       | 18       |                           
| queue_model          | QueueModel                | queue-model.xml                 | 3        |                           
| collect              | None                      | mxcollect.xml                   | 3        | No object loaded          
| energy_scan          | EnergyScanMockup          | energyscan-mockup.xml           | 3        |                           
| offline_processing   | OfflineProcessingMockup   | offline-processing-mockup.xml   | 7        |                           
| online_processing    | OnlineProcessingMockup    | online-processing-mockup.xml    | 9        |                           
| characterisation     | P11EDNACharacterisation   | characterisation.xml            | 11       |                           
| beamline             | Beamline                  | beamline_config.yml             | 4297     | Done loading contents     
+==================================================================================================================+

2024-09-06 14:12 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        return self._beam_info_dict
after explicit conversion to the list() it goes away.

2024-09-06 14:12 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        return self._beam_info_dict
python 3.11.9, Debian12

2024-09-06 14:13 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        return self._beam_info_dict
if it works for everyone else, I thought there is no need to touch Abstract Class.

2024-09-06 14:32 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        return self._beam_info_dict
Unfortunately I do not see what needs to be casted to list. Beam divergence is a tuple, which is constructed by two properties (see the init of the AbstractBeam)

2024-09-06 14:48 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        return self._beam_info_dict
Ok, got it now. It is not the divergence, but the beam size. The problem you have is that you cast to list before converting to numpy array,  while in the AbstractBeam min compares lists of floats. The code beneath takes care to choose what is actually you beam size, in case you have several values (e.g. you have the same beam size values when you have both aperture and definer, using the same aperture).

2024-09-06 15:35 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +        return self._beam_info_dict
OK, thanks for the comments. I just needed to convert to list and not the tuple.

2024-09-06 19:25 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +
Added, thanks.

2024-09-13 09:19 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11MachineInfo.py
> +
Thanks for the comment. It is now re-implemented using TangoMaschineInfo.

2024-09-13 09:19 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/MjpgStreamVideo.py
> +class MjpgStreamVideo(AbstractVideoDevice, HardwareObject):
Fixed.

2024-09-13 09:20 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/DigitalZoomMotor.py
> +class DigitalZoomMotor(AbstractMotor, HardwareObject):
Fixed.

2024-09-13 09:20 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/DigitalZoomMotor.py
> +            self.is_ready()
Fixed.

2024-09-13 09:21 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +        #     )
Fixed

2024-09-13 09:23 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +                # filepath = os.path.join(basepath, "%s_%d" % (prefix, runno))
Fixed.

2024-09-13 09:24 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +                # )
Fixed.

2024-09-13 09:25 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11NanoDiff.py
> +        #     self.init_ok = True
After test this part is still needed apparently. Keeping uncommented. Fixed.

2024-09-13 09:29 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11MachineInfo.py
> +"""
Reimplemeted. Fixed.

2024-09-13 09:41 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +            value = -1
Fixed. Good catch, thanks!

2024-09-13 09:49 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11DetectorDistance.py
> +                state = self.STATES.READY
Thanks for the catch. Fixed.

2024-09-13 11:14 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Transmission.py
>          limits = self.get_property("limits", None)
Thanks for the comment. Updated including doc strings. Closing.

2024-09-13 12:30 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +        """
Fixed. Thanks.

2024-09-13 12:31 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Collect.py
> +        """
Fixed.

2024-09-13 15:21 UTC, beteva approved these changes

2024-09-24 07:15 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +            value = -1
Sorry, one more time, I guess I've removed the wrong line :) Which one was that?

2024-09-24 10:51 UTC, agruzinov commented
Thanks everyone for the looking into it and nice suggestions. I've renamed it to WIP for now as it requere more testing.

2024-09-24 11:57 UTC, agruzinov commented on mxcubecore/HardwareObjects/MotorsNPosition.py
> +        self._updating_multi_value = True
Thanks for the proposal. I've updated it now.

2024-09-24 12:01 UTC, agruzinov commented on mxcubecore/HardwareObjects/MotorsNPosition.py
> +            return
@beteva Thanks for the suggestion about the NState! I've rewrote the beamstop, collimator, pinhole and diode motors to use this class instead of MultiNState. It required also to add respective changes to the qt code. I've tested it and it seems to be working for now with this updates. Could you please have  a look?

2024-09-25 08:34 UTC, rhfogh approved these changes
Approved on a lightning glance. We have been over this before, the non-DESY parts look innocuous, the DESY parts can be left to the DESY people, and I am sure Antonia can vet MotorsNPosition. Let us get this merged, finally

2024-09-26 10:04 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/P11MachineInfo.py
> +
You can remove this, as it is already in the inherited class.

2024-09-26 10:07 UTC, beteva commented on mxcubecore/HardwareObjects/TangoMotor.py
> +        """Connects to all Tango channels and commands"""
Thanks for cleaning up

2024-09-26 10:08 UTC, beteva commented on mxcubecore/HardwareObjects/DESY/DigitalZoomMotor.py
> +class DigitalZoomMotor(AbstractMotor, HardwareObject):
Still unnecessary inheritance from HardwareObject

2024-09-26 11:51 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11MachineInfo.py
> +
Thanks for the comment! I was wondering is machine_state_brick in qt somehow in use. If I add it in the designer mode t is not seemed to be displaying anything and in the mock-up too...

2024-09-27 13:17 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11MachineInfo.py
> +
OK, it looks like it is ok for now. Closing.

2024-09-27 13:19 UTC, agruzinov commented on mxcubecore/HardwareObjects/DESY/P11Beam.py
> +            value = -1
Seems to work now. Closing.

2024-09-27 13:23 UTC, agruzinov commented on mxcubecore/HardwareObjects/MotorsNPosition.py
> +        self._updating_multi_value = True
@fabcor-maxiv , I've updated it according to the latest suggestions, but additionally the corresponding hardware objects are rewritten and using different class. And it also do not produce any reccurency errors. Ive tested it, and it seems to be happy, but I would keep this class as an emergency rollback solution if this is ok.

2024-10-01 12:49 UTC, merged

2024-10-01 12:49 UTC, beteva commented
@agruzinov I am merging your PR.
Could you, please,, try to make smaller PRs.  This way it is easier to review and thus should not take such long time to merge, as it was with this one. Also the rebase would be easier.
It would be great if you could run black on the PR related files only. People will be less reluctant to merge 😄

2024-10-01 13:22 UTC, agruzinov commented
@beteva Thank you and everyone for the suggestions. Unfortunately it is not always possible to make the PR smaller as there is still a development phase that require a lot of fixes in different places that could be done and tested only during sparse commissioning beam times, but I will try to. Cheers!