docs: XML to YAML config migration document
mxcube/mxcubecore pull request #992
Opened 2024-08-21 05:44 UTC by elmjag

Adds a documentation section 'YAML configuration migration', with details on how to migrate to YAML configration.

2024-08-21 07:47 UTC, fabcor-maxiv commented
Preview here: https://mxcubecore--992.org.readthedocs.build/en/992/dev/yaml_conf_migration.html

2024-08-21 08:10 UTC, fabcor-maxiv requested changes
Good stuff

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +When using a YAML file, you may need to update the python code of your hardware object.
```suggestion
When using a YAML file, you may need to update the Python code of your hardware object.
```

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +```
This will make we have the correct syntax highlighting

```suggestion
```yaml
```

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +  ...
Let's not put three dots like this. They have a particular meaning in YAML documents. They mark the end of the document. <https://yaml.org/spec/1.1/#document%20boundary%20marker/>

```suggestion
  # ...
```

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +...
```suggestion
# ...
```

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +  ...
```suggestion
  # ...
```

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +  ...
```suggestion
  # ...
```

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +  !!omap
No idea why we need the `!!omap`. Do we need it? I get that it is unrelated to the YAML configuration, I am curious.

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +The `_initialise_class` dictionary have been replaced by a `class` key-value pair.
Typo `s/have/has`.

But also I do not see any "key-value pair" in the example above.

```suggestion
The `_initialise_class` dictionary has been replaced by a `class` key-value pair.
```

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +  mxcubecore.HardwareObjects.Beamline.Beamline
This seems strange... Is it even valid YAML? See also below...

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +The `_objects` dictionary have been renamed to `objects`.
```suggestion
The `_objects` dictionary has been renamed to `objects`.
```

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +### new `configuration` dictionary
```suggestion
### New `configuration` dictionary
```

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +See the [YAML configuration migration](https://mxcubeweb.readthedocs.io/en/latest/dev/yaml_conf_migration.html)
I guess the document does not exist yet... and now there is a link to the current document (link to itself).

Anyway we should use better notation for the link, some relative link. I never remember what is the correct notation, maybe this:

```suggestion
See the [YAML configuration migration](something.md)
```

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +```
```suggestion
```xml
```

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +Gives the following equivalent configuration in YAML.
```suggestion
Gives the following equivalent configuration in YAML:
```

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +  lims: lims.yml
```suggestion
  session: session.yaml
  lims: lims.yaml
```

Ha! :D

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +```
In this case the Python syntax seems to be automatically detected, but better safe...

```suggestion
```python
```

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +```
```suggestion
Needs to be converted to one of the following styles:

    ```python
    def init(self):
        # 'config' attribute option
        foo = self.config.foo
     ```

    ```python
    def init(self):
        # 'get_property()' method option
        foo = self.get_property("foo")
     ```

```
Well, we don't need the extra indentation, but otherwise it messes up the formatting of he comment here.

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +```
```suggestion
```python
```

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +```
```suggestion
```yaml
```

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +    ClassName(name="role")
```suggestion
ClassName(name="role")
```

2024-08-21 08:10 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +```
```suggestion
```yaml
```

2024-08-22 06:24 UTC, elmjag commented on docs/source/dev/yaml_conf_migration.md
> +  ...
I think this syntax to show 'omitted parts' is just confusing. I have removed these lines. I think it's will be obvious for readers that's it's a truncated example.

2024-08-22 06:47 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +  ...
Sometimes I write `# [...]` I do not know if it makes it clearer that it is an ellipsis, that stuff is omitted.

2024-08-22 06:48 UTC, fabcor-maxiv approved these changes

2024-08-23 11:13 UTC, rhfogh commented on docs/source/dev/yaml_conf_migration.md
> +  !!omap
We need it to ensure that the order of objects is maintained and reproducible, so we can control th loading order. `omap` gives an ordered dictionary rather than just a plain dictionary. We need the objects ordered, because the initialisation of certain objects may depend on other objects having been in initialised already.

2024-08-23 11:18 UTC, rhfogh commented on docs/source/dev/yaml_conf_migration.md
> +  mxcubecore.HardwareObjects.Beamline.Beamline
Maybe it should just say:

class:  mxcubecore.HardwareObjects.Beamline.Beamline

on a single line?

2024-08-23 11:22 UTC, rhfogh approved these changes
Very nice!. Thanks.

2024-08-23 11:25 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +  !!omap
OK, so we write it as a list in the Yaml document (with `!!omap`) and the Python Yaml parser (`ruamel.yaml`) transforms it into a `dict` (which is ordered by default on recent Python versions or `OrderedDict` on older Python versions).

2024-08-23 11:35 UTC, rhfogh commented on docs/source/dev/yaml_conf_migration.md
> +  !!omap
I would not call it a  list. This is not a list of dictionaries (which it would be if you used the same syntax but removed the '!omap'), it is an ordered mapping. But apart from that we agree.

2024-08-23 14:29 UTC, elmjag commented on docs/source/dev/yaml_conf_migration.md
> +See the [YAML configuration migration](https://mxcubeweb.readthedocs.io/en/latest/dev/yaml_conf_migration.html)
This is link to MXCube-**web** documentation. This URL will be valid once we merge the `xml_yaml_conversation` branch there.

Here is documentation it refers to:
https://github.com/mxcube/mxcubeweb/blob/xml_yaml_conversion/docs/source/dev/yaml_conf_migration.md

2024-08-23 14:32 UTC, elmjag commented on docs/source/dev/yaml_conf_migration.md
> +```
added!

2024-08-23 14:34 UTC, elmjag commented on docs/source/dev/yaml_conf_migration.md
> +```
added

2024-08-23 14:59 UTC, fabcor-maxiv commented on docs/source/dev/yaml_conf_migration.md
> +See the [YAML configuration migration](https://mxcubeweb.readthedocs.io/en/latest/dev/yaml_conf_migration.html)
Ah... right... there is a way to make it cleaner still, but I do not remember, so I guess it is fine for now : )

2024-08-23 15:07 UTC, elmjag commented on docs/source/dev/yaml_conf_migration.md
> +  mxcubecore.HardwareObjects.Beamline.Beamline
I'm not a YAML lawyer, so I have no idea if it's valid YAML or not, but...

Interesting enough, both version works! But, let's go with the one-line version. I like the compactness of that style.

2024-08-26 06:33 UTC, fabcor-maxiv approved these changes

2024-08-26 06:44 UTC, merged